/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.skautik.sdk.api;

import com.skautik.sdk.ApiClient;
import com.skautik.sdk.ApiException;
import com.skautik.sdk.ApiResponse;
import com.skautik.sdk.Configuration;
import com.skautik.sdk.Pair;

import com.skautik.sdk.model.Envelope;
import java.io.File;
import com.skautik.sdk.model.ImportList;
import com.skautik.sdk.model.ImportRecordList;
import com.skautik.sdk.model.ImportResponse;
import com.skautik.sdk.model.ImportSourceInput;
import com.skautik.sdk.model.ImportSourceList;
import com.skautik.sdk.model.ImportSourceResponse;
import com.skautik.sdk.model.Problem;
import com.skautik.sdk.model.SourceUpdate;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ImportsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public ImportsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ImportsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Start an import
   * Upload a file, or point us at one, and process it.  Accepts a multipart upload or a URL we fetch. Validation runs first and the whole file is rejected if it cannot be parsed; individual records that fail are reported without stopping the rest, unless you ask for all-or-nothing.  Requires the &#x60;imports:write&#x60; scope.
   * @param format Format of the file being sent. (required)
   * @param mode Incremental updates what the file contains and leaves the rest alone. A full sync also withdraws anything absent from it, which is why it is not the default. (optional, default to incremental)
   * @param sourceId Import source this transfer belongs to, when it comes from a standing connector rather than a one-off upload. (optional)
   * @param dryRun Parse and report what would change without writing anything. Worth doing once with a new mapping. (optional)
   * @param filename Original filename, recorded on the run so a failure can be traced back to the file that caused it. (optional)
   * @param confirmShrink Allow a full sync that would withdraw a large share of the source&#39;s portfolio. Without it, a delivery carrying far fewer records than the source currently holds has its withdrawals held back and the run is reported as partial, on the assumption that the export was truncated. Set this when the reduction is real. (optional)
   * @param idempotencyKey Prevents a retried upload from being processed twice. (optional)
   * @param _file The payload. Mutually exclusive with url. (optional)
   * @return ImportResponse
   * @throws ApiException if fails to make API call
   */
  public ImportResponse createImport(@javax.annotation.Nonnull String format, @javax.annotation.Nullable String mode, @javax.annotation.Nullable String sourceId, @javax.annotation.Nullable Boolean dryRun, @javax.annotation.Nullable String filename, @javax.annotation.Nullable Boolean confirmShrink, @javax.annotation.Nullable String idempotencyKey, @javax.annotation.Nullable File _file) throws ApiException {
    return createImport(format, mode, sourceId, dryRun, filename, confirmShrink, idempotencyKey, _file, null);
  }

  /**
   * Start an import
   * Upload a file, or point us at one, and process it.  Accepts a multipart upload or a URL we fetch. Validation runs first and the whole file is rejected if it cannot be parsed; individual records that fail are reported without stopping the rest, unless you ask for all-or-nothing.  Requires the &#x60;imports:write&#x60; scope.
   * @param format Format of the file being sent. (required)
   * @param mode Incremental updates what the file contains and leaves the rest alone. A full sync also withdraws anything absent from it, which is why it is not the default. (optional, default to incremental)
   * @param sourceId Import source this transfer belongs to, when it comes from a standing connector rather than a one-off upload. (optional)
   * @param dryRun Parse and report what would change without writing anything. Worth doing once with a new mapping. (optional)
   * @param filename Original filename, recorded on the run so a failure can be traced back to the file that caused it. (optional)
   * @param confirmShrink Allow a full sync that would withdraw a large share of the source&#39;s portfolio. Without it, a delivery carrying far fewer records than the source currently holds has its withdrawals held back and the run is reported as partial, on the assumption that the export was truncated. Set this when the reduction is real. (optional)
   * @param idempotencyKey Prevents a retried upload from being processed twice. (optional)
   * @param _file The payload. Mutually exclusive with url. (optional)
   * @param headers Optional headers to include in the request
   * @return ImportResponse
   * @throws ApiException if fails to make API call
   */
  public ImportResponse createImport(@javax.annotation.Nonnull String format, @javax.annotation.Nullable String mode, @javax.annotation.Nullable String sourceId, @javax.annotation.Nullable Boolean dryRun, @javax.annotation.Nullable String filename, @javax.annotation.Nullable Boolean confirmShrink, @javax.annotation.Nullable String idempotencyKey, @javax.annotation.Nullable File _file, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportResponse> localVarResponse = createImportWithHttpInfo(format, mode, sourceId, dryRun, filename, confirmShrink, idempotencyKey, _file, headers);
    return localVarResponse.getData();
  }

  /**
   * Start an import
   * Upload a file, or point us at one, and process it.  Accepts a multipart upload or a URL we fetch. Validation runs first and the whole file is rejected if it cannot be parsed; individual records that fail are reported without stopping the rest, unless you ask for all-or-nothing.  Requires the &#x60;imports:write&#x60; scope.
   * @param format Format of the file being sent. (required)
   * @param mode Incremental updates what the file contains and leaves the rest alone. A full sync also withdraws anything absent from it, which is why it is not the default. (optional, default to incremental)
   * @param sourceId Import source this transfer belongs to, when it comes from a standing connector rather than a one-off upload. (optional)
   * @param dryRun Parse and report what would change without writing anything. Worth doing once with a new mapping. (optional)
   * @param filename Original filename, recorded on the run so a failure can be traced back to the file that caused it. (optional)
   * @param confirmShrink Allow a full sync that would withdraw a large share of the source&#39;s portfolio. Without it, a delivery carrying far fewer records than the source currently holds has its withdrawals held back and the run is reported as partial, on the assumption that the export was truncated. Set this when the reduction is real. (optional)
   * @param idempotencyKey Prevents a retried upload from being processed twice. (optional)
   * @param _file The payload. Mutually exclusive with url. (optional)
   * @return ApiResponse&lt;ImportResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportResponse> createImportWithHttpInfo(@javax.annotation.Nonnull String format, @javax.annotation.Nullable String mode, @javax.annotation.Nullable String sourceId, @javax.annotation.Nullable Boolean dryRun, @javax.annotation.Nullable String filename, @javax.annotation.Nullable Boolean confirmShrink, @javax.annotation.Nullable String idempotencyKey, @javax.annotation.Nullable File _file) throws ApiException {
    return createImportWithHttpInfo(format, mode, sourceId, dryRun, filename, confirmShrink, idempotencyKey, _file, null);
  }

  /**
   * Start an import
   * Upload a file, or point us at one, and process it.  Accepts a multipart upload or a URL we fetch. Validation runs first and the whole file is rejected if it cannot be parsed; individual records that fail are reported without stopping the rest, unless you ask for all-or-nothing.  Requires the &#x60;imports:write&#x60; scope.
   * @param format Format of the file being sent. (required)
   * @param mode Incremental updates what the file contains and leaves the rest alone. A full sync also withdraws anything absent from it, which is why it is not the default. (optional, default to incremental)
   * @param sourceId Import source this transfer belongs to, when it comes from a standing connector rather than a one-off upload. (optional)
   * @param dryRun Parse and report what would change without writing anything. Worth doing once with a new mapping. (optional)
   * @param filename Original filename, recorded on the run so a failure can be traced back to the file that caused it. (optional)
   * @param confirmShrink Allow a full sync that would withdraw a large share of the source&#39;s portfolio. Without it, a delivery carrying far fewer records than the source currently holds has its withdrawals held back and the run is reported as partial, on the assumption that the export was truncated. Set this when the reduction is real. (optional)
   * @param idempotencyKey Prevents a retried upload from being processed twice. (optional)
   * @param _file The payload. Mutually exclusive with url. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportResponse> createImportWithHttpInfo(@javax.annotation.Nonnull String format, @javax.annotation.Nullable String mode, @javax.annotation.Nullable String sourceId, @javax.annotation.Nullable Boolean dryRun, @javax.annotation.Nullable String filename, @javax.annotation.Nullable Boolean confirmShrink, @javax.annotation.Nullable String idempotencyKey, @javax.annotation.Nullable File _file, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createImportRequestBuilder(format, mode, sourceId, dryRun, filename, confirmShrink, idempotencyKey, _file, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createImport", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportResponse>() {});
        

        return new ApiResponse<ImportResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createImportRequestBuilder(@javax.annotation.Nonnull String format, @javax.annotation.Nullable String mode, @javax.annotation.Nullable String sourceId, @javax.annotation.Nullable Boolean dryRun, @javax.annotation.Nullable String filename, @javax.annotation.Nullable Boolean confirmShrink, @javax.annotation.Nullable String idempotencyKey, @javax.annotation.Nullable File _file, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'format' is set
    if (format == null) {
      throw new ApiException(400, "Missing the required parameter 'format' when calling createImport");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/imports";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));
    localVarQueryParameterBaseName = "mode";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("mode", mode));
    localVarQueryParameterBaseName = "source_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("source_id", sourceId));
    localVarQueryParameterBaseName = "dry_run";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("dry_run", dryRun));
    localVarQueryParameterBaseName = "filename";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("filename", filename));
    localVarQueryParameterBaseName = "confirm_shrink";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("confirm_shrink", confirmShrink));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    multiPartBuilder.addBinaryBody("file", _file);
    hasFiles = true;
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create an import source
   * A standing connector that imports on a schedule.  Configure once and stop thinking about it. A source holds the format, the delivery method, the field mapping, and the deletion policy, and every run against it produces an import you can inspect.  Requires the &#x60;imports:write&#x60; scope.
   * @param importSourceInput  (required)
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse createImportSource(@javax.annotation.Nonnull ImportSourceInput importSourceInput) throws ApiException {
    return createImportSource(importSourceInput, null);
  }

  /**
   * Create an import source
   * A standing connector that imports on a schedule.  Configure once and stop thinking about it. A source holds the format, the delivery method, the field mapping, and the deletion policy, and every run against it produces an import you can inspect.  Requires the &#x60;imports:write&#x60; scope.
   * @param importSourceInput  (required)
   * @param headers Optional headers to include in the request
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse createImportSource(@javax.annotation.Nonnull ImportSourceInput importSourceInput, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportSourceResponse> localVarResponse = createImportSourceWithHttpInfo(importSourceInput, headers);
    return localVarResponse.getData();
  }

  /**
   * Create an import source
   * A standing connector that imports on a schedule.  Configure once and stop thinking about it. A source holds the format, the delivery method, the field mapping, and the deletion policy, and every run against it produces an import you can inspect.  Requires the &#x60;imports:write&#x60; scope.
   * @param importSourceInput  (required)
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> createImportSourceWithHttpInfo(@javax.annotation.Nonnull ImportSourceInput importSourceInput) throws ApiException {
    return createImportSourceWithHttpInfo(importSourceInput, null);
  }

  /**
   * Create an import source
   * A standing connector that imports on a schedule.  Configure once and stop thinking about it. A source holds the format, the delivery method, the field mapping, and the deletion policy, and every run against it produces an import you can inspect.  Requires the &#x60;imports:write&#x60; scope.
   * @param importSourceInput  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> createImportSourceWithHttpInfo(@javax.annotation.Nonnull ImportSourceInput importSourceInput, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createImportSourceRequestBuilder(importSourceInput, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createImportSource", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportSourceResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportSourceResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportSourceResponse>() {});
        

        return new ApiResponse<ImportSourceResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createImportSourceRequestBuilder(@javax.annotation.Nonnull ImportSourceInput importSourceInput, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'importSourceInput' is set
    if (importSourceInput == null) {
      throw new ApiException(400, "Missing the required parameter 'importSourceInput' when calling createImportSource");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/import-sources";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(importSourceInput);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete an import source
   * Stop importing from this connector.  Deleting a source stops future runs. It does not withdraw the properties it created, which stay under your organisation until you withdraw them yourself.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteImportSource(@javax.annotation.Nonnull String sourceId) throws ApiException {
    deleteImportSource(sourceId, null);
  }

  /**
   * Delete an import source
   * Stop importing from this connector.  Deleting a source stops future runs. It does not withdraw the properties it created, which stay under your organisation until you withdraw them yourself.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteImportSource(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    deleteImportSourceWithHttpInfo(sourceId, headers);
  }

  /**
   * Delete an import source
   * Stop importing from this connector.  Deleting a source stops future runs. It does not withdraw the properties it created, which stay under your organisation until you withdraw them yourself.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId) throws ApiException {
    return deleteImportSourceWithHttpInfo(sourceId, null);
  }

  /**
   * Delete an import source
   * Stop importing from this connector.  Deleting a source stops future runs. It does not withdraw the properties it created, which stay under your organisation until you withdraw them yourself.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteImportSourceRequestBuilder(sourceId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteImportSource", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteImportSourceRequestBuilder(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sourceId' is set
    if (sourceId == null) {
      throw new ApiException(400, "Missing the required parameter 'sourceId' when calling deleteImportSource");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/import-sources/{source_id}"
        .replace("{source_id}", ApiClient.urlEncode(sourceId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/problem+json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve an import
   * Progress, counts, and a summary of what changed.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @return ImportResponse
   * @throws ApiException if fails to make API call
   */
  public ImportResponse getImport(@javax.annotation.Nonnull String importId) throws ApiException {
    return getImport(importId, null);
  }

  /**
   * Retrieve an import
   * Progress, counts, and a summary of what changed.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ImportResponse
   * @throws ApiException if fails to make API call
   */
  public ImportResponse getImport(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportResponse> localVarResponse = getImportWithHttpInfo(importId, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve an import
   * Progress, counts, and a summary of what changed.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @return ApiResponse&lt;ImportResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportResponse> getImportWithHttpInfo(@javax.annotation.Nonnull String importId) throws ApiException {
    return getImportWithHttpInfo(importId, null);
  }

  /**
   * Retrieve an import
   * Progress, counts, and a summary of what changed.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportResponse> getImportWithHttpInfo(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getImportRequestBuilder(importId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getImport", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportResponse>() {});
        

        return new ApiResponse<ImportResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getImportRequestBuilder(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'importId' is set
    if (importId == null) {
      throw new ApiException(400, "Missing the required parameter 'importId' when calling getImport");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/imports/{import_id}"
        .replace("{import_id}", ApiClient.urlEncode(importId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve an import source
   * Configuration and recent run health.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse getImportSource(@javax.annotation.Nonnull String sourceId) throws ApiException {
    return getImportSource(sourceId, null);
  }

  /**
   * Retrieve an import source
   * Configuration and recent run health.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse getImportSource(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportSourceResponse> localVarResponse = getImportSourceWithHttpInfo(sourceId, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve an import source
   * Configuration and recent run health.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> getImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId) throws ApiException {
    return getImportSourceWithHttpInfo(sourceId, null);
  }

  /**
   * Retrieve an import source
   * Configuration and recent run health.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> getImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getImportSourceRequestBuilder(sourceId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getImportSource", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportSourceResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportSourceResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportSourceResponse>() {});
        

        return new ApiResponse<ImportSourceResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getImportSourceRequestBuilder(@javax.annotation.Nonnull String sourceId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sourceId' is set
    if (sourceId == null) {
      throw new ApiException(400, "Missing the required parameter 'sourceId' when calling getImportSource");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/import-sources/{source_id}"
        .replace("{source_id}", ApiClient.urlEncode(sourceId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List accepted formats and columns
   * What an import may carry: the formats that work today, every CSV column, and the limits.  Served from the same tables the parser reads, so it cannot fall behind what is actually accepted. Worth calling once when you build the integration rather than transcribing the column list from this page.  Requires the &#x60;imports:write&#x60; scope.
   * @return Envelope
   * @throws ApiException if fails to make API call
   */
  public Envelope importFormats() throws ApiException {
    return importFormats(null);
  }

  /**
   * List accepted formats and columns
   * What an import may carry: the formats that work today, every CSV column, and the limits.  Served from the same tables the parser reads, so it cannot fall behind what is actually accepted. Worth calling once when you build the integration rather than transcribing the column list from this page.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return Envelope
   * @throws ApiException if fails to make API call
   */
  public Envelope importFormats(Map<String, String> headers) throws ApiException {
    ApiResponse<Envelope> localVarResponse = importFormatsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List accepted formats and columns
   * What an import may carry: the formats that work today, every CSV column, and the limits.  Served from the same tables the parser reads, so it cannot fall behind what is actually accepted. Worth calling once when you build the integration rather than transcribing the column list from this page.  Requires the &#x60;imports:write&#x60; scope.
   * @return ApiResponse&lt;Envelope&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Envelope> importFormatsWithHttpInfo() throws ApiException {
    return importFormatsWithHttpInfo(null);
  }

  /**
   * List accepted formats and columns
   * What an import may carry: the formats that work today, every CSV column, and the limits.  Served from the same tables the parser reads, so it cannot fall behind what is actually accepted. Worth calling once when you build the integration rather than transcribing the column list from this page.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Envelope&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Envelope> importFormatsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = importFormatsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("importFormats", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Envelope>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Envelope responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Envelope>() {});
        

        return new ApiResponse<Envelope>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder importFormatsRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/imports/formats";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List import records
   * Per-record outcome, including why any failed.  Filter to failed to get the working list for a fix. Each entry names the source identifier and the line or element it came from, so a problem can be found in your export rather than guessed at.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @return ImportRecordList
   * @throws ApiException if fails to make API call
   */
  public ImportRecordList listImportRecords(@javax.annotation.Nonnull String importId) throws ApiException {
    return listImportRecords(importId, null);
  }

  /**
   * List import records
   * Per-record outcome, including why any failed.  Filter to failed to get the working list for a fix. Each entry names the source identifier and the line or element it came from, so a problem can be found in your export rather than guessed at.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ImportRecordList
   * @throws ApiException if fails to make API call
   */
  public ImportRecordList listImportRecords(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportRecordList> localVarResponse = listImportRecordsWithHttpInfo(importId, headers);
    return localVarResponse.getData();
  }

  /**
   * List import records
   * Per-record outcome, including why any failed.  Filter to failed to get the working list for a fix. Each entry names the source identifier and the line or element it came from, so a problem can be found in your export rather than guessed at.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @return ApiResponse&lt;ImportRecordList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportRecordList> listImportRecordsWithHttpInfo(@javax.annotation.Nonnull String importId) throws ApiException {
    return listImportRecordsWithHttpInfo(importId, null);
  }

  /**
   * List import records
   * Per-record outcome, including why any failed.  Filter to failed to get the working list for a fix. Each entry names the source identifier and the line or element it came from, so a problem can be found in your export rather than guessed at.  Requires the &#x60;imports:write&#x60; scope.
   * @param importId Import identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportRecordList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportRecordList> listImportRecordsWithHttpInfo(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listImportRecordsRequestBuilder(importId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listImportRecords", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportRecordList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportRecordList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportRecordList>() {});
        

        return new ApiResponse<ImportRecordList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listImportRecordsRequestBuilder(@javax.annotation.Nonnull String importId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'importId' is set
    if (importId == null) {
      throw new ApiException(400, "Missing the required parameter 'importId' when calling listImportRecords");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/imports/{import_id}/records"
        .replace("{import_id}", ApiClient.urlEncode(importId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List import sources
   * Every standing connector your organisation has configured.  Credentials are never returned. A fetched source often holds the login for your own server in its URL, so the URL comes back with the password removed.  Requires the &#x60;imports:write&#x60; scope.
   * @return ImportSourceList
   * @throws ApiException if fails to make API call
   */
  public ImportSourceList listImportSources() throws ApiException {
    return listImportSources(null);
  }

  /**
   * List import sources
   * Every standing connector your organisation has configured.  Credentials are never returned. A fetched source often holds the login for your own server in its URL, so the URL comes back with the password removed.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ImportSourceList
   * @throws ApiException if fails to make API call
   */
  public ImportSourceList listImportSources(Map<String, String> headers) throws ApiException {
    ApiResponse<ImportSourceList> localVarResponse = listImportSourcesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List import sources
   * Every standing connector your organisation has configured.  Credentials are never returned. A fetched source often holds the login for your own server in its URL, so the URL comes back with the password removed.  Requires the &#x60;imports:write&#x60; scope.
   * @return ApiResponse&lt;ImportSourceList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceList> listImportSourcesWithHttpInfo() throws ApiException {
    return listImportSourcesWithHttpInfo(null);
  }

  /**
   * List import sources
   * Every standing connector your organisation has configured.  Credentials are never returned. A fetched source often holds the login for your own server in its URL, so the URL comes back with the password removed.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportSourceList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceList> listImportSourcesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listImportSourcesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listImportSources", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportSourceList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportSourceList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportSourceList>() {});
        

        return new ApiResponse<ImportSourceList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listImportSourcesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/import-sources";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List imports
   * Import history for your organisation.  Requires the &#x60;imports:write&#x60; scope.
   * @return ImportList
   * @throws ApiException if fails to make API call
   */
  public ImportList listImports() throws ApiException {
    return listImports(null);
  }

  /**
   * List imports
   * Import history for your organisation.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ImportList
   * @throws ApiException if fails to make API call
   */
  public ImportList listImports(Map<String, String> headers) throws ApiException {
    ApiResponse<ImportList> localVarResponse = listImportsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List imports
   * Import history for your organisation.  Requires the &#x60;imports:write&#x60; scope.
   * @return ApiResponse&lt;ImportList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportList> listImportsWithHttpInfo() throws ApiException {
    return listImportsWithHttpInfo(null);
  }

  /**
   * List imports
   * Import history for your organisation.  Requires the &#x60;imports:write&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportList> listImportsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listImportsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listImports", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportList>() {});
        

        return new ApiResponse<ImportList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listImportsRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/imports";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update an import source
   * Change the mapping, schedule, or deletion policy.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param sourceUpdate  (required)
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse updateImportSource(@javax.annotation.Nonnull String sourceId, @javax.annotation.Nonnull SourceUpdate sourceUpdate) throws ApiException {
    return updateImportSource(sourceId, sourceUpdate, null);
  }

  /**
   * Update an import source
   * Change the mapping, schedule, or deletion policy.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param sourceUpdate  (required)
   * @param headers Optional headers to include in the request
   * @return ImportSourceResponse
   * @throws ApiException if fails to make API call
   */
  public ImportSourceResponse updateImportSource(@javax.annotation.Nonnull String sourceId, @javax.annotation.Nonnull SourceUpdate sourceUpdate, Map<String, String> headers) throws ApiException {
    ApiResponse<ImportSourceResponse> localVarResponse = updateImportSourceWithHttpInfo(sourceId, sourceUpdate, headers);
    return localVarResponse.getData();
  }

  /**
   * Update an import source
   * Change the mapping, schedule, or deletion policy.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param sourceUpdate  (required)
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> updateImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId, @javax.annotation.Nonnull SourceUpdate sourceUpdate) throws ApiException {
    return updateImportSourceWithHttpInfo(sourceId, sourceUpdate, null);
  }

  /**
   * Update an import source
   * Change the mapping, schedule, or deletion policy.  Requires the &#x60;imports:write&#x60; scope.
   * @param sourceId Source identifier. (required)
   * @param sourceUpdate  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImportSourceResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImportSourceResponse> updateImportSourceWithHttpInfo(@javax.annotation.Nonnull String sourceId, @javax.annotation.Nonnull SourceUpdate sourceUpdate, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateImportSourceRequestBuilder(sourceId, sourceUpdate, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateImportSource", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImportSourceResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImportSourceResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImportSourceResponse>() {});
        

        return new ApiResponse<ImportSourceResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateImportSourceRequestBuilder(@javax.annotation.Nonnull String sourceId, @javax.annotation.Nonnull SourceUpdate sourceUpdate, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sourceId' is set
    if (sourceId == null) {
      throw new ApiException(400, "Missing the required parameter 'sourceId' when calling updateImportSource");
    }
    // verify the required parameter 'sourceUpdate' is set
    if (sourceUpdate == null) {
      throw new ApiException(400, "Missing the required parameter 'sourceUpdate' when calling updateImportSource");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/import-sources/{source_id}"
        .replace("{source_id}", ApiClient.urlEncode(sourceId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(sourceUpdate);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
