/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.skautik.sdk.api;

import com.skautik.sdk.ApiClient;
import com.skautik.sdk.ApiException;
import com.skautik.sdk.ApiResponse;
import com.skautik.sdk.Configuration;
import com.skautik.sdk.Pair;

import java.math.BigDecimal;
import com.skautik.sdk.model.CreatePropertyRequest;
import com.skautik.sdk.model.Envelope;
import java.io.File;
import com.skautik.sdk.model.ImageList;
import com.skautik.sdk.model.ImageResponse;
import com.skautik.sdk.model.PriceObservationList;
import com.skautik.sdk.model.Problem;
import com.skautik.sdk.model.PropertyList;
import com.skautik.sdk.model.PropertyPage;
import com.skautik.sdk.model.PropertyResponse;
import com.skautik.sdk.model.SearchPropertiesRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PropertiesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PropertiesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PropertiesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a property
   * Publish a record from your own inventory.  Send an Idempotency-Key so a retried request cannot create a duplicate listing. Records created this way belong to your organisation and are the only ones your key may modify.  Requires the &#x60;properties:write&#x60; scope.
   * @param createPropertyRequest  (required)
   * @param idempotencyKey Unique per logical creation. Replaying the same key returns the original result rather than creating a second record. (optional)
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse createProperty(@javax.annotation.Nonnull CreatePropertyRequest createPropertyRequest, @javax.annotation.Nullable String idempotencyKey) throws ApiException {
    return createProperty(createPropertyRequest, idempotencyKey, null);
  }

  /**
   * Create a property
   * Publish a record from your own inventory.  Send an Idempotency-Key so a retried request cannot create a duplicate listing. Records created this way belong to your organisation and are the only ones your key may modify.  Requires the &#x60;properties:write&#x60; scope.
   * @param createPropertyRequest  (required)
   * @param idempotencyKey Unique per logical creation. Replaying the same key returns the original result rather than creating a second record. (optional)
   * @param headers Optional headers to include in the request
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse createProperty(@javax.annotation.Nonnull CreatePropertyRequest createPropertyRequest, @javax.annotation.Nullable String idempotencyKey, Map<String, String> headers) throws ApiException {
    ApiResponse<PropertyResponse> localVarResponse = createPropertyWithHttpInfo(createPropertyRequest, idempotencyKey, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a property
   * Publish a record from your own inventory.  Send an Idempotency-Key so a retried request cannot create a duplicate listing. Records created this way belong to your organisation and are the only ones your key may modify.  Requires the &#x60;properties:write&#x60; scope.
   * @param createPropertyRequest  (required)
   * @param idempotencyKey Unique per logical creation. Replaying the same key returns the original result rather than creating a second record. (optional)
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> createPropertyWithHttpInfo(@javax.annotation.Nonnull CreatePropertyRequest createPropertyRequest, @javax.annotation.Nullable String idempotencyKey) throws ApiException {
    return createPropertyWithHttpInfo(createPropertyRequest, idempotencyKey, null);
  }

  /**
   * Create a property
   * Publish a record from your own inventory.  Send an Idempotency-Key so a retried request cannot create a duplicate listing. Records created this way belong to your organisation and are the only ones your key may modify.  Requires the &#x60;properties:write&#x60; scope.
   * @param createPropertyRequest  (required)
   * @param idempotencyKey Unique per logical creation. Replaying the same key returns the original result rather than creating a second record. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> createPropertyWithHttpInfo(@javax.annotation.Nonnull CreatePropertyRequest createPropertyRequest, @javax.annotation.Nullable String idempotencyKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createPropertyRequestBuilder(createPropertyRequest, idempotencyKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createProperty", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PropertyResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PropertyResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PropertyResponse>() {});
        

        return new ApiResponse<PropertyResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createPropertyRequestBuilder(@javax.annotation.Nonnull CreatePropertyRequest createPropertyRequest, @javax.annotation.Nullable String idempotencyKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createPropertyRequest' is set
    if (createPropertyRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createPropertyRequest' when calling createProperty");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createPropertyRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Withdraw a property
   * Take one of your records off the market.  Withdrawal is not deletion. The record moves to withdrawn, disappears from search, and keeps its price history so past analysis stays intelligible. A record owned by an import source is refused, because the next run would bring it straight back: withdraw it at the source instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to withdraw. (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteProperty(@javax.annotation.Nonnull String propertyId) throws ApiException {
    deleteProperty(propertyId, null);
  }

  /**
   * Withdraw a property
   * Take one of your records off the market.  Withdrawal is not deletion. The record moves to withdrawn, disappears from search, and keeps its price history so past analysis stays intelligible. A record owned by an import source is refused, because the next run would bring it straight back: withdraw it at the source instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to withdraw. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteProperty(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    deletePropertyWithHttpInfo(propertyId, headers);
  }

  /**
   * Withdraw a property
   * Take one of your records off the market.  Withdrawal is not deletion. The record moves to withdrawn, disappears from search, and keeps its price history so past analysis stays intelligible. A record owned by an import source is refused, because the next run would bring it straight back: withdraw it at the source instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to withdraw. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deletePropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId) throws ApiException {
    return deletePropertyWithHttpInfo(propertyId, null);
  }

  /**
   * Withdraw a property
   * Take one of your records off the market.  Withdrawal is not deletion. The record moves to withdrawn, disappears from search, and keeps its price history so past analysis stays intelligible. A record owned by an import source is refused, because the next run would bring it straight back: withdraw it at the source instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to withdraw. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deletePropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deletePropertyRequestBuilder(propertyId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteProperty", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deletePropertyRequestBuilder(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling deleteProperty");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/problem+json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete an image
   * Remove an image from a record you published.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param imageId Image identifier. (required)
   * @throws ApiException if fails to make API call
   */
  public void deletePropertyImage(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull String imageId) throws ApiException {
    deletePropertyImage(propertyId, imageId, null);
  }

  /**
   * Delete an image
   * Remove an image from a record you published.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param imageId Image identifier. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deletePropertyImage(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull String imageId, Map<String, String> headers) throws ApiException {
    deletePropertyImageWithHttpInfo(propertyId, imageId, headers);
  }

  /**
   * Delete an image
   * Remove an image from a record you published.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param imageId Image identifier. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deletePropertyImageWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull String imageId) throws ApiException {
    return deletePropertyImageWithHttpInfo(propertyId, imageId, null);
  }

  /**
   * Delete an image
   * Remove an image from a record you published.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param imageId Image identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deletePropertyImageWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull String imageId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deletePropertyImageRequestBuilder(propertyId, imageId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deletePropertyImage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deletePropertyImageRequestBuilder(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull String imageId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling deletePropertyImage");
    }
    // verify the required parameter 'imageId' is set
    if (imageId == null) {
      throw new ApiException(400, "Missing the required parameter 'imageId' when calling deletePropertyImage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}/images/{image_id}"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()))
        .replace("{image_id}", ApiClient.urlEncode(imageId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/problem+json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve a property
   * One property with its full attribute set.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Identifier returned by any collection endpoint. (required)
   * @param expand Related resources to inline. (optional)
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse getProperty(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable List<String> expand) throws ApiException {
    return getProperty(propertyId, expand, null);
  }

  /**
   * Retrieve a property
   * One property with its full attribute set.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Identifier returned by any collection endpoint. (required)
   * @param expand Related resources to inline. (optional)
   * @param headers Optional headers to include in the request
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse getProperty(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {
    ApiResponse<PropertyResponse> localVarResponse = getPropertyWithHttpInfo(propertyId, expand, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve a property
   * One property with its full attribute set.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Identifier returned by any collection endpoint. (required)
   * @param expand Related resources to inline. (optional)
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> getPropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable List<String> expand) throws ApiException {
    return getPropertyWithHttpInfo(propertyId, expand, null);
  }

  /**
   * Retrieve a property
   * One property with its full attribute set.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Identifier returned by any collection endpoint. (required)
   * @param expand Related resources to inline. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> getPropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPropertyRequestBuilder(propertyId, expand, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getProperty", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PropertyResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PropertyResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PropertyResponse>() {});
        

        return new ApiResponse<PropertyResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPropertyRequestBuilder(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling getProperty");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "expand";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "expand", expand));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List properties
   * Page through the catalogue with filters.  The workhorse read endpoint. Filters combine with AND. Anything omitted is unconstrained, so an unfiltered call returns the whole catalogue in cursor order.  Requires the &#x60;properties:read&#x60; scope.
   * @param market Market identifier from the markets endpoint. (optional)
   * @param district District within the market. Repeatable for a union. (optional)
   * @param transactionType Restrict to sales or rentals. (optional)
   * @param propertyType Repeatable for a union. (optional)
   * @param priceMin Inclusive lower bound, in minor units. (optional)
   * @param priceMax Inclusive upper bound, in minor units. (optional)
   * @param bedroomsMin Inclusive lower bound on bedroom count. (optional)
   * @param areaMin Inclusive lower bound on living area, in square metres. (optional)
   * @param status Defaults to active. Pass explicitly to include withdrawn records. (optional, default to active)
   * @param updatedSince RFC 3339 timestamp. The efficient way to keep a mirror in step without re-reading everything. (optional)
   * @param limit Records per page, 1 to 200. (optional, default to 50)
   * @param cursor Opaque pointer from the previous response. Omit for the first page. Cursors are stable across inserts, so paging never skips or repeats a record the way an offset does. (optional)
   * @param sort Field to order by. Prefix with a minus for descending. Ties break on id, so paging is deterministic. (optional, default to -listed_at)
   * @param fields Comma-separated list of fields to return. Trims payloads substantially when you only need a few. (optional)
   * @param expand Comma-separated related resources to inline rather than fetch separately. (optional)
   * @return PropertyPage
   * @throws ApiException if fails to make API call
   */
  public PropertyPage listProperties(@javax.annotation.Nullable String market, @javax.annotation.Nullable List<String> district, @javax.annotation.Nullable String transactionType, @javax.annotation.Nullable List<String> propertyType, @javax.annotation.Nullable Integer priceMin, @javax.annotation.Nullable Integer priceMax, @javax.annotation.Nullable Integer bedroomsMin, @javax.annotation.Nullable BigDecimal areaMin, @javax.annotation.Nullable String status, @javax.annotation.Nullable String updatedSince, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String sort, @javax.annotation.Nullable List<String> fields, @javax.annotation.Nullable List<String> expand) throws ApiException {
    return listProperties(market, district, transactionType, propertyType, priceMin, priceMax, bedroomsMin, areaMin, status, updatedSince, limit, cursor, sort, fields, expand, null);
  }

  /**
   * List properties
   * Page through the catalogue with filters.  The workhorse read endpoint. Filters combine with AND. Anything omitted is unconstrained, so an unfiltered call returns the whole catalogue in cursor order.  Requires the &#x60;properties:read&#x60; scope.
   * @param market Market identifier from the markets endpoint. (optional)
   * @param district District within the market. Repeatable for a union. (optional)
   * @param transactionType Restrict to sales or rentals. (optional)
   * @param propertyType Repeatable for a union. (optional)
   * @param priceMin Inclusive lower bound, in minor units. (optional)
   * @param priceMax Inclusive upper bound, in minor units. (optional)
   * @param bedroomsMin Inclusive lower bound on bedroom count. (optional)
   * @param areaMin Inclusive lower bound on living area, in square metres. (optional)
   * @param status Defaults to active. Pass explicitly to include withdrawn records. (optional, default to active)
   * @param updatedSince RFC 3339 timestamp. The efficient way to keep a mirror in step without re-reading everything. (optional)
   * @param limit Records per page, 1 to 200. (optional, default to 50)
   * @param cursor Opaque pointer from the previous response. Omit for the first page. Cursors are stable across inserts, so paging never skips or repeats a record the way an offset does. (optional)
   * @param sort Field to order by. Prefix with a minus for descending. Ties break on id, so paging is deterministic. (optional, default to -listed_at)
   * @param fields Comma-separated list of fields to return. Trims payloads substantially when you only need a few. (optional)
   * @param expand Comma-separated related resources to inline rather than fetch separately. (optional)
   * @param headers Optional headers to include in the request
   * @return PropertyPage
   * @throws ApiException if fails to make API call
   */
  public PropertyPage listProperties(@javax.annotation.Nullable String market, @javax.annotation.Nullable List<String> district, @javax.annotation.Nullable String transactionType, @javax.annotation.Nullable List<String> propertyType, @javax.annotation.Nullable Integer priceMin, @javax.annotation.Nullable Integer priceMax, @javax.annotation.Nullable Integer bedroomsMin, @javax.annotation.Nullable BigDecimal areaMin, @javax.annotation.Nullable String status, @javax.annotation.Nullable String updatedSince, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String sort, @javax.annotation.Nullable List<String> fields, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {
    ApiResponse<PropertyPage> localVarResponse = listPropertiesWithHttpInfo(market, district, transactionType, propertyType, priceMin, priceMax, bedroomsMin, areaMin, status, updatedSince, limit, cursor, sort, fields, expand, headers);
    return localVarResponse.getData();
  }

  /**
   * List properties
   * Page through the catalogue with filters.  The workhorse read endpoint. Filters combine with AND. Anything omitted is unconstrained, so an unfiltered call returns the whole catalogue in cursor order.  Requires the &#x60;properties:read&#x60; scope.
   * @param market Market identifier from the markets endpoint. (optional)
   * @param district District within the market. Repeatable for a union. (optional)
   * @param transactionType Restrict to sales or rentals. (optional)
   * @param propertyType Repeatable for a union. (optional)
   * @param priceMin Inclusive lower bound, in minor units. (optional)
   * @param priceMax Inclusive upper bound, in minor units. (optional)
   * @param bedroomsMin Inclusive lower bound on bedroom count. (optional)
   * @param areaMin Inclusive lower bound on living area, in square metres. (optional)
   * @param status Defaults to active. Pass explicitly to include withdrawn records. (optional, default to active)
   * @param updatedSince RFC 3339 timestamp. The efficient way to keep a mirror in step without re-reading everything. (optional)
   * @param limit Records per page, 1 to 200. (optional, default to 50)
   * @param cursor Opaque pointer from the previous response. Omit for the first page. Cursors are stable across inserts, so paging never skips or repeats a record the way an offset does. (optional)
   * @param sort Field to order by. Prefix with a minus for descending. Ties break on id, so paging is deterministic. (optional, default to -listed_at)
   * @param fields Comma-separated list of fields to return. Trims payloads substantially when you only need a few. (optional)
   * @param expand Comma-separated related resources to inline rather than fetch separately. (optional)
   * @return ApiResponse&lt;PropertyPage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyPage> listPropertiesWithHttpInfo(@javax.annotation.Nullable String market, @javax.annotation.Nullable List<String> district, @javax.annotation.Nullable String transactionType, @javax.annotation.Nullable List<String> propertyType, @javax.annotation.Nullable Integer priceMin, @javax.annotation.Nullable Integer priceMax, @javax.annotation.Nullable Integer bedroomsMin, @javax.annotation.Nullable BigDecimal areaMin, @javax.annotation.Nullable String status, @javax.annotation.Nullable String updatedSince, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String sort, @javax.annotation.Nullable List<String> fields, @javax.annotation.Nullable List<String> expand) throws ApiException {
    return listPropertiesWithHttpInfo(market, district, transactionType, propertyType, priceMin, priceMax, bedroomsMin, areaMin, status, updatedSince, limit, cursor, sort, fields, expand, null);
  }

  /**
   * List properties
   * Page through the catalogue with filters.  The workhorse read endpoint. Filters combine with AND. Anything omitted is unconstrained, so an unfiltered call returns the whole catalogue in cursor order.  Requires the &#x60;properties:read&#x60; scope.
   * @param market Market identifier from the markets endpoint. (optional)
   * @param district District within the market. Repeatable for a union. (optional)
   * @param transactionType Restrict to sales or rentals. (optional)
   * @param propertyType Repeatable for a union. (optional)
   * @param priceMin Inclusive lower bound, in minor units. (optional)
   * @param priceMax Inclusive upper bound, in minor units. (optional)
   * @param bedroomsMin Inclusive lower bound on bedroom count. (optional)
   * @param areaMin Inclusive lower bound on living area, in square metres. (optional)
   * @param status Defaults to active. Pass explicitly to include withdrawn records. (optional, default to active)
   * @param updatedSince RFC 3339 timestamp. The efficient way to keep a mirror in step without re-reading everything. (optional)
   * @param limit Records per page, 1 to 200. (optional, default to 50)
   * @param cursor Opaque pointer from the previous response. Omit for the first page. Cursors are stable across inserts, so paging never skips or repeats a record the way an offset does. (optional)
   * @param sort Field to order by. Prefix with a minus for descending. Ties break on id, so paging is deterministic. (optional, default to -listed_at)
   * @param fields Comma-separated list of fields to return. Trims payloads substantially when you only need a few. (optional)
   * @param expand Comma-separated related resources to inline rather than fetch separately. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PropertyPage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyPage> listPropertiesWithHttpInfo(@javax.annotation.Nullable String market, @javax.annotation.Nullable List<String> district, @javax.annotation.Nullable String transactionType, @javax.annotation.Nullable List<String> propertyType, @javax.annotation.Nullable Integer priceMin, @javax.annotation.Nullable Integer priceMax, @javax.annotation.Nullable Integer bedroomsMin, @javax.annotation.Nullable BigDecimal areaMin, @javax.annotation.Nullable String status, @javax.annotation.Nullable String updatedSince, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String sort, @javax.annotation.Nullable List<String> fields, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPropertiesRequestBuilder(market, district, transactionType, propertyType, priceMin, priceMax, bedroomsMin, areaMin, status, updatedSince, limit, cursor, sort, fields, expand, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listProperties", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PropertyPage>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PropertyPage responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PropertyPage>() {});
        

        return new ApiResponse<PropertyPage>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPropertiesRequestBuilder(@javax.annotation.Nullable String market, @javax.annotation.Nullable List<String> district, @javax.annotation.Nullable String transactionType, @javax.annotation.Nullable List<String> propertyType, @javax.annotation.Nullable Integer priceMin, @javax.annotation.Nullable Integer priceMax, @javax.annotation.Nullable Integer bedroomsMin, @javax.annotation.Nullable BigDecimal areaMin, @javax.annotation.Nullable String status, @javax.annotation.Nullable String updatedSince, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable String sort, @javax.annotation.Nullable List<String> fields, @javax.annotation.Nullable List<String> expand, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "market";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("market", market));
    localVarQueryParameterBaseName = "district";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "district", district));
    localVarQueryParameterBaseName = "transaction_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("transaction_type", transactionType));
    localVarQueryParameterBaseName = "property_type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "property_type", propertyType));
    localVarQueryParameterBaseName = "price_min";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("price_min", priceMin));
    localVarQueryParameterBaseName = "price_max";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("price_max", priceMax));
    localVarQueryParameterBaseName = "bedrooms_min";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("bedrooms_min", bedroomsMin));
    localVarQueryParameterBaseName = "area_min";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("area_min", areaMin));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "updated_since";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("updated_since", updatedSince));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "fields";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields", fields));
    localVarQueryParameterBaseName = "expand";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "expand", expand));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List images
   * Image records for a property, in display order.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @return ImageList
   * @throws ApiException if fails to make API call
   */
  public ImageList listPropertyImages(@javax.annotation.Nonnull String propertyId) throws ApiException {
    return listPropertyImages(propertyId, null);
  }

  /**
   * List images
   * Image records for a property, in display order.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ImageList
   * @throws ApiException if fails to make API call
   */
  public ImageList listPropertyImages(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    ApiResponse<ImageList> localVarResponse = listPropertyImagesWithHttpInfo(propertyId, headers);
    return localVarResponse.getData();
  }

  /**
   * List images
   * Image records for a property, in display order.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @return ApiResponse&lt;ImageList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImageList> listPropertyImagesWithHttpInfo(@javax.annotation.Nonnull String propertyId) throws ApiException {
    return listPropertyImagesWithHttpInfo(propertyId, null);
  }

  /**
   * List images
   * Image records for a property, in display order.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImageList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImageList> listPropertyImagesWithHttpInfo(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPropertyImagesRequestBuilder(propertyId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listPropertyImages", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImageList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImageList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImageList>() {});
        

        return new ApiResponse<ImageList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPropertyImagesRequestBuilder(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling listPropertyImages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}/images"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Price history
   * Every asking price we observed while tracking the listing.  These are advertised prices, not transacted ones. A property may well have sold for something quite different from its final asking price.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @return PriceObservationList
   * @throws ApiException if fails to make API call
   */
  public PriceObservationList propertyPriceHistory(@javax.annotation.Nonnull String propertyId) throws ApiException {
    return propertyPriceHistory(propertyId, null);
  }

  /**
   * Price history
   * Every asking price we observed while tracking the listing.  These are advertised prices, not transacted ones. A property may well have sold for something quite different from its final asking price.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param headers Optional headers to include in the request
   * @return PriceObservationList
   * @throws ApiException if fails to make API call
   */
  public PriceObservationList propertyPriceHistory(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    ApiResponse<PriceObservationList> localVarResponse = propertyPriceHistoryWithHttpInfo(propertyId, headers);
    return localVarResponse.getData();
  }

  /**
   * Price history
   * Every asking price we observed while tracking the listing.  These are advertised prices, not transacted ones. A property may well have sold for something quite different from its final asking price.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @return ApiResponse&lt;PriceObservationList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PriceObservationList> propertyPriceHistoryWithHttpInfo(@javax.annotation.Nonnull String propertyId) throws ApiException {
    return propertyPriceHistoryWithHttpInfo(propertyId, null);
  }

  /**
   * Price history
   * Every asking price we observed while tracking the listing.  These are advertised prices, not transacted ones. A property may well have sold for something quite different from its final asking price.  Requires the &#x60;properties:read&#x60; scope.
   * @param propertyId Property identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PriceObservationList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PriceObservationList> propertyPriceHistoryWithHttpInfo(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = propertyPriceHistoryRequestBuilder(propertyId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("propertyPriceHistory", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PriceObservationList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PriceObservationList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PriceObservationList>() {});
        

        return new ApiResponse<PriceObservationList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder propertyPriceHistoryRequestBuilder(@javax.annotation.Nonnull String propertyId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling propertyPriceHistory");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}/price-history"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search properties
   * Semantic and geographic search that is too complex for a query string.  Takes a natural-language query, a drawn polygon, or both. Results come back ranked by relevance rather than by a sortable column, so this endpoint ignores the sort parameter. It is a POST because a polygon does not belong in a URL, not because it changes anything.  Requires the &#x60;properties:read&#x60; scope.
   * @param searchPropertiesRequest  (optional)
   * @return Envelope
   * @throws ApiException if fails to make API call
   */
  public Envelope searchProperties(@javax.annotation.Nullable SearchPropertiesRequest searchPropertiesRequest) throws ApiException {
    return searchProperties(searchPropertiesRequest, null);
  }

  /**
   * Search properties
   * Semantic and geographic search that is too complex for a query string.  Takes a natural-language query, a drawn polygon, or both. Results come back ranked by relevance rather than by a sortable column, so this endpoint ignores the sort parameter. It is a POST because a polygon does not belong in a URL, not because it changes anything.  Requires the &#x60;properties:read&#x60; scope.
   * @param searchPropertiesRequest  (optional)
   * @param headers Optional headers to include in the request
   * @return Envelope
   * @throws ApiException if fails to make API call
   */
  public Envelope searchProperties(@javax.annotation.Nullable SearchPropertiesRequest searchPropertiesRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<Envelope> localVarResponse = searchPropertiesWithHttpInfo(searchPropertiesRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Search properties
   * Semantic and geographic search that is too complex for a query string.  Takes a natural-language query, a drawn polygon, or both. Results come back ranked by relevance rather than by a sortable column, so this endpoint ignores the sort parameter. It is a POST because a polygon does not belong in a URL, not because it changes anything.  Requires the &#x60;properties:read&#x60; scope.
   * @param searchPropertiesRequest  (optional)
   * @return ApiResponse&lt;Envelope&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Envelope> searchPropertiesWithHttpInfo(@javax.annotation.Nullable SearchPropertiesRequest searchPropertiesRequest) throws ApiException {
    return searchPropertiesWithHttpInfo(searchPropertiesRequest, null);
  }

  /**
   * Search properties
   * Semantic and geographic search that is too complex for a query string.  Takes a natural-language query, a drawn polygon, or both. Results come back ranked by relevance rather than by a sortable column, so this endpoint ignores the sort parameter. It is a POST because a polygon does not belong in a URL, not because it changes anything.  Requires the &#x60;properties:read&#x60; scope.
   * @param searchPropertiesRequest  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Envelope&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Envelope> searchPropertiesWithHttpInfo(@javax.annotation.Nullable SearchPropertiesRequest searchPropertiesRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchPropertiesRequestBuilder(searchPropertiesRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchProperties", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Envelope>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Envelope responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Envelope>() {});
        

        return new ApiResponse<Envelope>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchPropertiesRequestBuilder(@javax.annotation.Nullable SearchPropertiesRequest searchPropertiesRequest, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/search";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(searchPropertiesRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Similar properties
   * Comparable records, for context or valuation support.  Similarity blends location, size, type, and condition. It is a convenience, not an appraisal, and comparables thin out quickly in low-supply areas.  Requires the &#x60;properties:read&#x60; scope.  Availability: Growth and above.
   * @param propertyId Property to compare against. (required)
   * @param limit Comparables to return, 1 to 50. (optional, default to 10)
   * @return PropertyList
   * @throws ApiException if fails to make API call
   */
  public PropertyList similarProperties(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable Integer limit) throws ApiException {
    return similarProperties(propertyId, limit, null);
  }

  /**
   * Similar properties
   * Comparable records, for context or valuation support.  Similarity blends location, size, type, and condition. It is a convenience, not an appraisal, and comparables thin out quickly in low-supply areas.  Requires the &#x60;properties:read&#x60; scope.  Availability: Growth and above.
   * @param propertyId Property to compare against. (required)
   * @param limit Comparables to return, 1 to 50. (optional, default to 10)
   * @param headers Optional headers to include in the request
   * @return PropertyList
   * @throws ApiException if fails to make API call
   */
  public PropertyList similarProperties(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<PropertyList> localVarResponse = similarPropertiesWithHttpInfo(propertyId, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Similar properties
   * Comparable records, for context or valuation support.  Similarity blends location, size, type, and condition. It is a convenience, not an appraisal, and comparables thin out quickly in low-supply areas.  Requires the &#x60;properties:read&#x60; scope.  Availability: Growth and above.
   * @param propertyId Property to compare against. (required)
   * @param limit Comparables to return, 1 to 50. (optional, default to 10)
   * @return ApiResponse&lt;PropertyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyList> similarPropertiesWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable Integer limit) throws ApiException {
    return similarPropertiesWithHttpInfo(propertyId, limit, null);
  }

  /**
   * Similar properties
   * Comparable records, for context or valuation support.  Similarity blends location, size, type, and condition. It is a convenience, not an appraisal, and comparables thin out quickly in low-supply areas.  Requires the &#x60;properties:read&#x60; scope.  Availability: Growth and above.
   * @param propertyId Property to compare against. (required)
   * @param limit Comparables to return, 1 to 50. (optional, default to 10)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PropertyList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyList> similarPropertiesWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = similarPropertiesRequestBuilder(propertyId, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("similarProperties", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PropertyList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PropertyList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PropertyList>() {});
        

        return new ApiResponse<PropertyList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder similarPropertiesRequestBuilder(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling similarProperties");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}/similar"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a property
   * Change fields on a record you published.  A partial update: send only what changes. Send If-Match with the ETag from your last read to avoid overwriting a concurrent edit. A record owned by an import source is refused here, because the next run would revert whatever you wrote: change it in the system that feeds the import instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to update. (required)
   * @param ifMatch ETag from your last read. Rejected with 412 if the record moved on. (optional)
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse updateProperty(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable String ifMatch) throws ApiException {
    return updateProperty(propertyId, ifMatch, null);
  }

  /**
   * Update a property
   * Change fields on a record you published.  A partial update: send only what changes. Send If-Match with the ETag from your last read to avoid overwriting a concurrent edit. A record owned by an import source is refused here, because the next run would revert whatever you wrote: change it in the system that feeds the import instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to update. (required)
   * @param ifMatch ETag from your last read. Rejected with 412 if the record moved on. (optional)
   * @param headers Optional headers to include in the request
   * @return PropertyResponse
   * @throws ApiException if fails to make API call
   */
  public PropertyResponse updateProperty(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable String ifMatch, Map<String, String> headers) throws ApiException {
    ApiResponse<PropertyResponse> localVarResponse = updatePropertyWithHttpInfo(propertyId, ifMatch, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a property
   * Change fields on a record you published.  A partial update: send only what changes. Send If-Match with the ETag from your last read to avoid overwriting a concurrent edit. A record owned by an import source is refused here, because the next run would revert whatever you wrote: change it in the system that feeds the import instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to update. (required)
   * @param ifMatch ETag from your last read. Rejected with 412 if the record moved on. (optional)
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> updatePropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable String ifMatch) throws ApiException {
    return updatePropertyWithHttpInfo(propertyId, ifMatch, null);
  }

  /**
   * Update a property
   * Change fields on a record you published.  A partial update: send only what changes. Send If-Match with the ETag from your last read to avoid overwriting a concurrent edit. A record owned by an import source is refused here, because the next run would revert whatever you wrote: change it in the system that feeds the import instead.  Requires the &#x60;properties:write&#x60; scope.
   * @param propertyId Property to update. (required)
   * @param ifMatch ETag from your last read. Rejected with 412 if the record moved on. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PropertyResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PropertyResponse> updatePropertyWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable String ifMatch, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updatePropertyRequestBuilder(propertyId, ifMatch, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateProperty", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PropertyResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PropertyResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PropertyResponse>() {});
        

        return new ApiResponse<PropertyResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updatePropertyRequestBuilder(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nullable String ifMatch, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling updateProperty");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (ifMatch != null) {
      localVarRequestBuilder.header("If-Match", ifMatch.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Upload an image
   * Attach an image to a record you published.  Multipart upload. JPEG, PNG, or WebP up to 12 MB. Upload only images you hold the rights to: property photography is usually licensed to an agent rather than owned outright.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property to attach to. (required)
   * @param _file Image payload. (required)
   * @param position Display order. The image at position 0 is the primary one. (optional)
   * @return ImageResponse
   * @throws ApiException if fails to make API call
   */
  public ImageResponse uploadPropertyImage(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable Integer position) throws ApiException {
    return uploadPropertyImage(propertyId, _file, position, null);
  }

  /**
   * Upload an image
   * Attach an image to a record you published.  Multipart upload. JPEG, PNG, or WebP up to 12 MB. Upload only images you hold the rights to: property photography is usually licensed to an agent rather than owned outright.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property to attach to. (required)
   * @param _file Image payload. (required)
   * @param position Display order. The image at position 0 is the primary one. (optional)
   * @param headers Optional headers to include in the request
   * @return ImageResponse
   * @throws ApiException if fails to make API call
   */
  public ImageResponse uploadPropertyImage(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable Integer position, Map<String, String> headers) throws ApiException {
    ApiResponse<ImageResponse> localVarResponse = uploadPropertyImageWithHttpInfo(propertyId, _file, position, headers);
    return localVarResponse.getData();
  }

  /**
   * Upload an image
   * Attach an image to a record you published.  Multipart upload. JPEG, PNG, or WebP up to 12 MB. Upload only images you hold the rights to: property photography is usually licensed to an agent rather than owned outright.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property to attach to. (required)
   * @param _file Image payload. (required)
   * @param position Display order. The image at position 0 is the primary one. (optional)
   * @return ApiResponse&lt;ImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImageResponse> uploadPropertyImageWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable Integer position) throws ApiException {
    return uploadPropertyImageWithHttpInfo(propertyId, _file, position, null);
  }

  /**
   * Upload an image
   * Attach an image to a record you published.  Multipart upload. JPEG, PNG, or WebP up to 12 MB. Upload only images you hold the rights to: property photography is usually licensed to an agent rather than owned outright.  Requires the &#x60;images:write&#x60; scope.
   * @param propertyId Property to attach to. (required)
   * @param _file Image payload. (required)
   * @param position Display order. The image at position 0 is the primary one. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ImageResponse> uploadPropertyImageWithHttpInfo(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable Integer position, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = uploadPropertyImageRequestBuilder(propertyId, _file, position, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("uploadPropertyImage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ImageResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ImageResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ImageResponse>() {});
        

        return new ApiResponse<ImageResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder uploadPropertyImageRequestBuilder(@javax.annotation.Nonnull String propertyId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable Integer position, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'propertyId' is set
    if (propertyId == null) {
      throw new ApiException(400, "Missing the required parameter 'propertyId' when calling uploadPropertyImage");
    }
    // verify the required parameter '_file' is set
    if (_file == null) {
      throw new ApiException(400, "Missing the required parameter '_file' when calling uploadPropertyImage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/properties/{property_id}/images"
        .replace("{property_id}", ApiClient.urlEncode(propertyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    multiPartBuilder.addBinaryBody("file", _file);
    hasFiles = true;
    if (position != null) {
        multiPartBuilder.addTextBody("position", position.toString());
    }
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
