// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

import com.skautik.sdk.api.ExportsApi;
import com.skautik.sdk.model.*;

import java.io.File;
import java.math.BigDecimal;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;

/** Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready. */
public final class ExportsResource {

    private final ExportsApi api;

    ExportsResource(ExportsApi api) {
        this.api = api;
    }

    /**
     * List exports
     *
     * <p>Requires the {@code exports:create} scope.
     */
    public ExportList list() throws ApiException {
        return api.listExports();
    }

    /**
     * Request an export
     *
     * <p>Requires the {@code exports:create} scope.
     */
    public ExportResponse create(ExportInput exportInput) throws ApiException {
        return api.createExport(exportInput);
    }

    /**
     * Retrieve an export
     *
     * <p>Requires the {@code exports:create} scope.
     */
    public ExportResponse get(String exportId) throws ApiException {
        return api.getExport(exportId);
    }
}
