// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

import java.math.BigDecimal;
import java.util.List;

/**
 * What to ask for from {@code getDistrict}.
 *
 * <p>Every field is optional, and unset means unconstrained. Built rather than
 * passed positionally, because the call underneath takes 4
 * arguments in order and Java cannot name them at the call site.
 */
public final class GetDistrictOptions {

    private final String period;
    private final String propertyType;

    private GetDistrictOptions(String period, String propertyType) {
        this.period = period;
        this.propertyType = propertyType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public String period() {
        return period;
    }

    public String propertyType() {
        return propertyType;
    }

    public static final class Builder {

        private String period;
        private String propertyType;

        public Builder period(String period) {
            this.period = period;
            return this;
        }

        public Builder propertyType(String propertyType) {
            this.propertyType = propertyType;
            return this;
        }

        public GetDistrictOptions build() {
            return new GetDistrictOptions(period, propertyType);
        }
    }
}
