// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

import java.math.BigDecimal;
import java.util.List;

/**
 * What to ask for from {@code get}.
 *
 * <p>Every field is optional, and unset means unconstrained. Built rather than
 * passed positionally, because the call underneath takes 3
 * arguments in order and Java cannot name them at the call site.
 */
public final class GetPropertyOptions {

    private final List<String> expand;
    private final String language;

    private GetPropertyOptions(List<String> expand, String language) {
        this.expand = expand;
        this.language = language;
    }

    public static Builder builder() {
        return new Builder();
    }

    public List<String> expand() {
        return expand;
    }

    public String language() {
        return language;
    }

    public static final class Builder {

        private List<String> expand;
        private String language;

        public Builder expand(List<String> expand) {
            this.expand = expand;
            return this;
        }

        public Builder language(String language) {
            this.language = language;
            return this;
        }

        public GetPropertyOptions build() {
            return new GetPropertyOptions(expand, language);
        }
    }
}
