// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

import java.math.BigDecimal;
import java.util.List;

/**
 * What to ask for from {@code list}.
 *
 * <p>Every field is optional, and unset means unconstrained. Built rather than
 * passed positionally, because the call underneath takes 16
 * arguments in order and Java cannot name them at the call site.
 */
public final class ListPropertiesOptions {

    private final String city;
    private final String district;
    private final String postalCode;
    private final String type;
    private final String transactionType;
    private final String status;
    private final String externalId;
    private final BigDecimal minPrice;
    private final BigDecimal maxPrice;
    private final BigDecimal minLivingArea;
    private final Integer minBedrooms;
    private final Integer limit;
    private final String cursor;
    private final String sort;
    private final List<String> expand;
    private final String language;

    private ListPropertiesOptions(String city, String district, String postalCode, String type, String transactionType, String status, String externalId, BigDecimal minPrice, BigDecimal maxPrice, BigDecimal minLivingArea, Integer minBedrooms, Integer limit, String cursor, String sort, List<String> expand, String language) {
        this.city = city;
        this.district = district;
        this.postalCode = postalCode;
        this.type = type;
        this.transactionType = transactionType;
        this.status = status;
        this.externalId = externalId;
        this.minPrice = minPrice;
        this.maxPrice = maxPrice;
        this.minLivingArea = minLivingArea;
        this.minBedrooms = minBedrooms;
        this.limit = limit;
        this.cursor = cursor;
        this.sort = sort;
        this.expand = expand;
        this.language = language;
    }

    public static Builder builder() {
        return new Builder();
    }

    public String city() {
        return city;
    }

    public String district() {
        return district;
    }

    public String postalCode() {
        return postalCode;
    }

    public String type() {
        return type;
    }

    public String transactionType() {
        return transactionType;
    }

    public String status() {
        return status;
    }

    public String externalId() {
        return externalId;
    }

    public BigDecimal minPrice() {
        return minPrice;
    }

    public BigDecimal maxPrice() {
        return maxPrice;
    }

    public BigDecimal minLivingArea() {
        return minLivingArea;
    }

    public Integer minBedrooms() {
        return minBedrooms;
    }

    public Integer limit() {
        return limit;
    }

    public String cursor() {
        return cursor;
    }

    public String sort() {
        return sort;
    }

    public List<String> expand() {
        return expand;
    }

    public String language() {
        return language;
    }

    /** The same options, reading from a different page. */
    public ListPropertiesOptions withCursor(String cursor) {
        return new ListPropertiesOptions(this.city, this.district, this.postalCode, this.type, this.transactionType, this.status, this.externalId, this.minPrice, this.maxPrice, this.minLivingArea, this.minBedrooms, this.limit, cursor, this.sort, this.expand, this.language);
    }

    public static final class Builder {

        private String city;
        private String district;
        private String postalCode;
        private String type;
        private String transactionType;
        private String status;
        private String externalId;
        private BigDecimal minPrice;
        private BigDecimal maxPrice;
        private BigDecimal minLivingArea;
        private Integer minBedrooms;
        private Integer limit;
        private String cursor;
        private String sort;
        private List<String> expand;
        private String language;

        public Builder city(String city) {
            this.city = city;
            return this;
        }

        public Builder district(String district) {
            this.district = district;
            return this;
        }

        public Builder postalCode(String postalCode) {
            this.postalCode = postalCode;
            return this;
        }

        public Builder type(String type) {
            this.type = type;
            return this;
        }

        public Builder transactionType(String transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        public Builder minPrice(BigDecimal minPrice) {
            this.minPrice = minPrice;
            return this;
        }

        public Builder maxPrice(BigDecimal maxPrice) {
            this.maxPrice = maxPrice;
            return this;
        }

        public Builder minLivingArea(BigDecimal minLivingArea) {
            this.minLivingArea = minLivingArea;
            return this;
        }

        public Builder minBedrooms(Integer minBedrooms) {
            this.minBedrooms = minBedrooms;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder sort(String sort) {
            this.sort = sort;
            return this;
        }

        public Builder expand(List<String> expand) {
            this.expand = expand;
            return this;
        }

        public Builder language(String language) {
            this.language = language;
            return this;
        }

        public ListPropertiesOptions build() {
            return new ListPropertiesOptions(city, district, postalCode, type, transactionType, status, externalId, minPrice, maxPrice, minLivingArea, minBedrooms, limit, cursor, sort, expand, language);
        }
    }
}
