// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

import com.skautik.sdk.api.MarketsApi;
import com.skautik.sdk.model.*;

import java.io.File;
import java.math.BigDecimal;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;

/** Where we have coverage, how each market is subdivided, and the aggregate statistics computed across it. */
public final class MarketsResource {

    private final MarketsApi api;

    MarketsResource(MarketsApi api) {
        this.api = api;
    }

    /**
     * List markets
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public CityList list() throws ApiException {
        return api.listMarkets();
    }

    /**
     * Retrieve a market
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public MarketResponse get(String city, GetMarketOptions options) throws ApiException {
        GetMarketOptions settings = options == null ? GetMarketOptions.builder().build() : options;
        return api.getMarket(city, settings.period(), settings.propertyType());
    }

    /**
     * Retrieve a market
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public MarketResponse get(String city) throws ApiException {
        return get(city, GetMarketOptions.builder().build());
    }

    /**
     * List districts
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public DistrictList listDistricts(String city) throws ApiException {
        return api.listDistricts(city);
    }

    /**
     * Retrieve a district
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public void getDistrict(String city, String district, GetDistrictOptions options) throws ApiException {
        GetDistrictOptions settings = options == null ? GetDistrictOptions.builder().build() : options;
        api.getDistrict(city, district, settings.period(), settings.propertyType());
    }

    /**
     * Retrieve a district
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public void getDistrict(String city, String district) throws ApiException {
        getDistrict(city, district, GetDistrictOptions.builder().build());
    }

    /**
     * Market statistics
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public SeriesResponse statistics(String city, MarketStatisticsOptions options) throws ApiException {
        MarketStatisticsOptions settings = options == null ? MarketStatisticsOptions.builder().build() : options;
        return api.marketStatistics(city, settings.propertyType(), settings.transactionType(), settings.interval(), settings.since());
    }

    /**
     * Market statistics
     *
     * <p>Requires the {@code markets:read} scope.
     */
    public SeriesResponse statistics(String city) throws ApiException {
        return statistics(city, MarketStatisticsOptions.builder().build());
    }
}
