// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

package com.skautik.sdk;

/**
 * A failure raised where a checked exception cannot be.
 *
 * <p>The paging iterators implement {@link java.util.Iterator}, whose methods
 * declare no checked exceptions, so an {@link ApiException} raised while
 * fetching the next page has nowhere to go. It is wrapped rather than
 * swallowed: {@code getCause} carries the original, with its status code and
 * response body.
 */
public final class SkautikException extends RuntimeException {

    public SkautikException(ApiException cause) {
        super(cause.getMessage(), cause);
    }

    /** The failure this wraps, with the status code and the response body. */
    public ApiException apiException() {
        return (ApiException) getCause();
    }
}
