/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * Bounds
 */
@JsonPropertyOrder({
  Bounds.JSON_PROPERTY_NE_LAT,
  Bounds.JSON_PROPERTY_NE_LNG,
  Bounds.JSON_PROPERTY_SW_LAT,
  Bounds.JSON_PROPERTY_SW_LNG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Bounds {
  public static final String JSON_PROPERTY_NE_LAT = "ne_lat";
  @javax.annotation.Nonnull
  private BigDecimal neLat;

  public static final String JSON_PROPERTY_NE_LNG = "ne_lng";
  @javax.annotation.Nonnull
  private BigDecimal neLng;

  public static final String JSON_PROPERTY_SW_LAT = "sw_lat";
  @javax.annotation.Nonnull
  private BigDecimal swLat;

  public static final String JSON_PROPERTY_SW_LNG = "sw_lng";
  @javax.annotation.Nonnull
  private BigDecimal swLng;

  public Bounds() { 
  }

  public Bounds neLat(@javax.annotation.Nonnull BigDecimal neLat) {
    this.neLat = neLat;
    return this;
  }

  /**
   * Get neLat
   * @return neLat
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NE_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getNeLat() {
    return neLat;
  }


  @JsonProperty(value = JSON_PROPERTY_NE_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNeLat(@javax.annotation.Nonnull BigDecimal neLat) {
    this.neLat = neLat;
  }


  public Bounds neLng(@javax.annotation.Nonnull BigDecimal neLng) {
    this.neLng = neLng;
    return this;
  }

  /**
   * Get neLng
   * @return neLng
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NE_LNG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getNeLng() {
    return neLng;
  }


  @JsonProperty(value = JSON_PROPERTY_NE_LNG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNeLng(@javax.annotation.Nonnull BigDecimal neLng) {
    this.neLng = neLng;
  }


  public Bounds swLat(@javax.annotation.Nonnull BigDecimal swLat) {
    this.swLat = swLat;
    return this;
  }

  /**
   * Get swLat
   * @return swLat
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SW_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getSwLat() {
    return swLat;
  }


  @JsonProperty(value = JSON_PROPERTY_SW_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSwLat(@javax.annotation.Nonnull BigDecimal swLat) {
    this.swLat = swLat;
  }


  public Bounds swLng(@javax.annotation.Nonnull BigDecimal swLng) {
    this.swLng = swLng;
    return this;
  }

  /**
   * Get swLng
   * @return swLng
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SW_LNG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getSwLng() {
    return swLng;
  }


  @JsonProperty(value = JSON_PROPERTY_SW_LNG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSwLng(@javax.annotation.Nonnull BigDecimal swLng) {
    this.swLng = swLng;
  }


  /**
   * Return true if this Bounds object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bounds bounds = (Bounds) o;
    return Objects.equals(this.neLat, bounds.neLat) &&
        Objects.equals(this.neLng, bounds.neLng) &&
        Objects.equals(this.swLat, bounds.swLat) &&
        Objects.equals(this.swLng, bounds.swLng);
  }

  @Override
  public int hashCode() {
    return Objects.hash(neLat, neLng, swLat, swLng);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bounds {\n");
    sb.append("    neLat: ").append(toIndentedString(neLat)).append("\n");
    sb.append("    neLng: ").append(toIndentedString(neLng)).append("\n");
    sb.append("    swLat: ").append(toIndentedString(swLat)).append("\n");
    sb.append("    swLng: ").append(toIndentedString(swLng)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ne_lat` to the URL query string
    if (getNeLat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sne_lat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNeLat()))));
    }

    // add `ne_lng` to the URL query string
    if (getNeLng() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sne_lng%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNeLng()))));
    }

    // add `sw_lat` to the URL query string
    if (getSwLat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssw_lat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSwLat()))));
    }

    // add `sw_lng` to the URL query string
    if (getSwLng() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssw_lng%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSwLng()))));
    }

    return joiner.toString();
  }
}

