/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * CreateGenerationRequest
 */
@JsonPropertyOrder({
  CreateGenerationRequest.JSON_PROPERTY_KIND,
  CreateGenerationRequest.JSON_PROPERTY_PROMPT,
  CreateGenerationRequest.JSON_PROPERTY_ROOM_TYPE,
  CreateGenerationRequest.JSON_PROPERTY_SOURCE_IMAGE_ID,
  CreateGenerationRequest.JSON_PROPERTY_STYLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateGenerationRequest {
  /**
   * The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.
   */
  public enum KindEnum {
    VIRTUAL_STAGING(String.valueOf("virtual_staging")),
    
    DECLUTTERING(String.valueOf("decluttering")),
    
    ENHANCEMENT(String.valueOf("enhancement"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nonnull
  private KindEnum kind;

  public static final String JSON_PROPERTY_PROMPT = "prompt";
  @javax.annotation.Nullable
  private String prompt;

  public static final String JSON_PROPERTY_ROOM_TYPE = "room_type";
  @javax.annotation.Nullable
  private String roomType;

  public static final String JSON_PROPERTY_SOURCE_IMAGE_ID = "source_image_id";
  @javax.annotation.Nonnull
  private String sourceImageId;

  public static final String JSON_PROPERTY_STYLE = "style";
  @javax.annotation.Nullable
  private String style;

  public CreateGenerationRequest() { 
  }

  public CreateGenerationRequest kind(@javax.annotation.Nonnull KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.
   * @return kind
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKind(@javax.annotation.Nonnull KindEnum kind) {
    this.kind = kind;
  }


  public CreateGenerationRequest prompt(@javax.annotation.Nullable String prompt) {
    this.prompt = prompt;
    return this;
  }

  /**
   * Up to 500 characters of additional direction. It is added to the instruction for the chosen kind and never replaces it, so it cannot be used to make the model do something unrelated.
   * @return prompt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROMPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrompt() {
    return prompt;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompt(@javax.annotation.Nullable String prompt) {
    this.prompt = prompt;
  }


  public CreateGenerationRequest roomType(@javax.annotation.Nullable String roomType) {
    this.roomType = roomType;
    return this;
  }

  /**
   * For virtual_staging: what the room is. Improves the result markedly. Defaults to a generic room.
   * @return roomType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROOM_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRoomType() {
    return roomType;
  }


  @JsonProperty(value = JSON_PROPERTY_ROOM_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomType(@javax.annotation.Nullable String roomType) {
    this.roomType = roomType;
  }


  public CreateGenerationRequest sourceImageId(@javax.annotation.Nonnull String sourceImageId) {
    this.sourceImageId = sourceImageId;
    return this;
  }

  /**
   * The image to transform. Must belong to one of your own properties; anything else answers 404, the same as an image that does not exist.
   * @return sourceImageId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE_IMAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSourceImageId() {
    return sourceImageId;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_IMAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceImageId(@javax.annotation.Nonnull String sourceImageId) {
    this.sourceImageId = sourceImageId;
  }


  public CreateGenerationRequest style(@javax.annotation.Nullable String style) {
    this.style = style;
    return this;
  }

  /**
   * For virtual_staging: the furnishing style. Defaults to contemporary.
   * @return style
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STYLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStyle() {
    return style;
  }


  @JsonProperty(value = JSON_PROPERTY_STYLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyle(@javax.annotation.Nullable String style) {
    this.style = style;
  }


  /**
   * Return true if this createGeneration_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateGenerationRequest createGenerationRequest = (CreateGenerationRequest) o;
    return Objects.equals(this.kind, createGenerationRequest.kind) &&
        Objects.equals(this.prompt, createGenerationRequest.prompt) &&
        Objects.equals(this.roomType, createGenerationRequest.roomType) &&
        Objects.equals(this.sourceImageId, createGenerationRequest.sourceImageId) &&
        Objects.equals(this.style, createGenerationRequest.style);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, prompt, roomType, sourceImageId, style);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateGenerationRequest {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    roomType: ").append(toIndentedString(roomType)).append("\n");
    sb.append("    sourceImageId: ").append(toIndentedString(sourceImageId)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `prompt` to the URL query string
    if (getPrompt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprompt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrompt()))));
    }

    // add `room_type` to the URL query string
    if (getRoomType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sroom_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRoomType()))));
    }

    // add `source_image_id` to the URL query string
    if (getSourceImageId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssource_image_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceImageId()))));
    }

    // add `style` to the URL query string
    if (getStyle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstyle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStyle()))));
    }

    return joiner.toString();
  }
}

