/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * CreateImportSourceRequest
 */
@JsonPropertyOrder({
  CreateImportSourceRequest.JSON_PROPERTY_DELETION_POLICY,
  CreateImportSourceRequest.JSON_PROPERTY_DELIVERY,
  CreateImportSourceRequest.JSON_PROPERTY_FORMAT,
  CreateImportSourceRequest.JSON_PROPERTY_MAPPING,
  CreateImportSourceRequest.JSON_PROPERTY_NAME,
  CreateImportSourceRequest.JSON_PROPERTY_SCHEDULE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateImportSourceRequest {
  /**
   * explicit_only honours deletion markers alone. absence_withdraws also withdraws anything missing from a full delivery, and should only be used where the format is a complete statement of stock.
   */
  public enum DeletionPolicyEnum {
    EXPLICIT_ONLY(String.valueOf("explicit_only")),
    
    ABSENCE_WITHDRAWS(String.valueOf("absence_withdraws"));

    private String value;

    DeletionPolicyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeletionPolicyEnum fromValue(String value) {
      for (DeletionPolicyEnum b : DeletionPolicyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELETION_POLICY = "deletion_policy";
  @javax.annotation.Nullable
  private DeletionPolicyEnum deletionPolicy = DeletionPolicyEnum.EXPLICIT_ONLY;

  public static final String JSON_PROPERTY_DELIVERY = "delivery";
  @javax.annotation.Nonnull
  private Map<String, Object> delivery = new HashMap<>();

  /**
   * Format this source delivers. Only csv and json parse today; the others are named in the schema and are refused here rather than accepted into a connector that would fail every run.
   */
  public enum FormatEnum {
    CSV(String.valueOf("csv")),
    
    JSON(String.valueOf("json"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nonnull
  private FormatEnum format;

  public static final String JSON_PROPERTY_MAPPING = "mapping";
  @javax.annotation.Nullable
  private Map<String, Object> mapping = new HashMap<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SCHEDULE = "schedule";
  @javax.annotation.Nullable
  private String schedule;

  public CreateImportSourceRequest() { 
  }

  public CreateImportSourceRequest deletionPolicy(@javax.annotation.Nullable DeletionPolicyEnum deletionPolicy) {
    this.deletionPolicy = deletionPolicy;
    return this;
  }

  /**
   * explicit_only honours deletion markers alone. absence_withdraws also withdraws anything missing from a full delivery, and should only be used where the format is a complete statement of stock.
   * @return deletionPolicy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETION_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeletionPolicyEnum getDeletionPolicy() {
    return deletionPolicy;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETION_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletionPolicy(@javax.annotation.Nullable DeletionPolicyEnum deletionPolicy) {
    this.deletionPolicy = deletionPolicy;
  }


  public CreateImportSourceRequest delivery(@javax.annotation.Nonnull Map<String, Object> delivery) {
    this.delivery = delivery;
    return this;
  }

  public CreateImportSourceRequest putDeliveryItem(String key, Object deliveryItem) {
    if (this.delivery == null) {
      this.delivery = new HashMap<>();
    }
    this.delivery.put(key, deliveryItem);
    return this;
  }

  /**
   * How data arrives. fetch_url pulls from a URL you give us on a schedule; api_push means you send us each delivery. SFTP drops are named in the schema and are not running yet, so asking for one is refused rather than answered with credentials for a host that would never accept them.
   * @return delivery
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERY, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getDelivery() {
    return delivery;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERY, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setDelivery(@javax.annotation.Nonnull Map<String, Object> delivery) {
    this.delivery = delivery;
  }


  public CreateImportSourceRequest format(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * Format this source delivers. Only csv and json parse today; the others are named in the schema and are refused here rather than accepted into a connector that would fail every run.
   * @return format
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
  }


  public CreateImportSourceRequest mapping(@javax.annotation.Nullable Map<String, Object> mapping) {
    this.mapping = mapping;
    return this;
  }

  public CreateImportSourceRequest putMappingItem(String key, Object mappingItem) {
    if (this.mapping == null) {
      this.mapping = new HashMap<>();
    }
    this.mapping.put(key, mappingItem);
    return this;
  }

  /**
   * Field mapping, for formats that need one. Omit for OpenImmo and RESO, which are already standardised.
   * @return mapping
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAPPING, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getMapping() {
    return mapping;
  }


  @JsonProperty(value = JSON_PROPERTY_MAPPING, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapping(@javax.annotation.Nullable Map<String, Object> mapping) {
    this.mapping = mapping;
  }


  public CreateImportSourceRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Your own label for the connector.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateImportSourceRequest schedule(@javax.annotation.Nullable String schedule) {
    this.schedule = schedule;
    return this;
  }

  /**
   * How often to pull, for fetched sources. Cron expression in UTC. Ignored for drops and pushes, which run on arrival.
   * @return schedule
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSchedule() {
    return schedule;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedule(@javax.annotation.Nullable String schedule) {
    this.schedule = schedule;
  }


  /**
   * Return true if this createImportSource_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateImportSourceRequest createImportSourceRequest = (CreateImportSourceRequest) o;
    return Objects.equals(this.deletionPolicy, createImportSourceRequest.deletionPolicy) &&
        Objects.equals(this.delivery, createImportSourceRequest.delivery) &&
        Objects.equals(this.format, createImportSourceRequest.format) &&
        Objects.equals(this.mapping, createImportSourceRequest.mapping) &&
        Objects.equals(this.name, createImportSourceRequest.name) &&
        Objects.equals(this.schedule, createImportSourceRequest.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deletionPolicy, delivery, format, mapping, name, schedule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateImportSourceRequest {\n");
    sb.append("    deletionPolicy: ").append(toIndentedString(deletionPolicy)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    mapping: ").append(toIndentedString(mapping)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deletion_policy` to the URL query string
    if (getDeletionPolicy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeletion_policy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeletionPolicy()))));
    }

    // add `delivery` to the URL query string
    if (getDelivery() != null) {
      for (String _key : getDelivery().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdelivery%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getDelivery().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getDelivery().get(_key)))));
      }
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sformat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFormat()))));
    }

    // add `mapping` to the URL query string
    if (getMapping() != null) {
      for (String _key : getMapping().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smapping%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getMapping().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getMapping().get(_key)))));
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `schedule` to the URL query string
    if (getSchedule() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sschedule%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSchedule()))));
    }

    return joiner.toString();
  }
}

