/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * ListingInput
 */
@JsonPropertyOrder({
  ListingInput.JSON_PROPERTY_CURRENCY,
  ListingInput.JSON_PROPERTY_DEPOSIT,
  ListingInput.JSON_PROPERTY_PRICE,
  ListingInput.JSON_PROPERTY_PRICE_PERIOD,
  ListingInput.JSON_PROPERTY_SERVICE_CHARGES,
  ListingInput.JSON_PROPERTY_STATUS,
  ListingInput.JSON_PROPERTY_TRANSACTION_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ListingInput {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_DEPOSIT = "deposit";
  @javax.annotation.Nullable
  private BigDecimal deposit;

  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_PRICE_PERIOD = "price_period";
  @javax.annotation.Nullable
  private String pricePeriod;

  public static final String JSON_PROPERTY_SERVICE_CHARGES = "service_charges";
  @javax.annotation.Nullable
  private BigDecimal serviceCharges;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transaction_type";
  @javax.annotation.Nullable
  private String transactionType;

  public ListingInput() { 
  }

  public ListingInput currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public ListingInput deposit(@javax.annotation.Nullable BigDecimal deposit) {
    this.deposit = deposit;
    return this;
  }

  /**
   * Get deposit
   * @return deposit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPOSIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getDeposit() {
    return deposit;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPOSIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeposit(@javax.annotation.Nullable BigDecimal deposit) {
    this.deposit = deposit;
  }


  public ListingInput price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public ListingInput pricePeriod(@javax.annotation.Nullable String pricePeriod) {
    this.pricePeriod = pricePeriod;
    return this;
  }

  /**
   * Get pricePeriod
   * @return pricePeriod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_PERIOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPricePeriod() {
    return pricePeriod;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_PERIOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricePeriod(@javax.annotation.Nullable String pricePeriod) {
    this.pricePeriod = pricePeriod;
  }


  public ListingInput serviceCharges(@javax.annotation.Nullable BigDecimal serviceCharges) {
    this.serviceCharges = serviceCharges;
    return this;
  }

  /**
   * Get serviceCharges
   * @return serviceCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getServiceCharges() {
    return serviceCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceCharges(@javax.annotation.Nullable BigDecimal serviceCharges) {
    this.serviceCharges = serviceCharges;
  }


  public ListingInput status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ListingInput transactionType(@javax.annotation.Nullable String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Get transactionType
   * @return transactionType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionType(@javax.annotation.Nullable String transactionType) {
    this.transactionType = transactionType;
  }


  /**
   * Return true if this ListingInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingInput listingInput = (ListingInput) o;
    return Objects.equals(this.currency, listingInput.currency) &&
        Objects.equals(this.deposit, listingInput.deposit) &&
        Objects.equals(this.price, listingInput.price) &&
        Objects.equals(this.pricePeriod, listingInput.pricePeriod) &&
        Objects.equals(this.serviceCharges, listingInput.serviceCharges) &&
        Objects.equals(this.status, listingInput.status) &&
        Objects.equals(this.transactionType, listingInput.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, deposit, price, pricePeriod, serviceCharges, status, transactionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingInput {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    deposit: ").append(toIndentedString(deposit)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    pricePeriod: ").append(toIndentedString(pricePeriod)).append("\n");
    sb.append("    serviceCharges: ").append(toIndentedString(serviceCharges)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `deposit` to the URL query string
    if (getDeposit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeposit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeposit()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `price_period` to the URL query string
    if (getPricePeriod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice_period%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPricePeriod()))));
    }

    // add `service_charges` to the URL query string
    if (getServiceCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sservice_charges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceCharges()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `transaction_type` to the URL query string
    if (getTransactionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransaction_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionType()))));
    }

    return joiner.toString();
  }
}

