/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * Listing
 */
@JsonPropertyOrder({
  Listing.JSON_PROPERTY_AVAILABLE_FROM,
  Listing.JSON_PROPERTY_COMMISSION_AMOUNT,
  Listing.JSON_PROPERTY_COMMISSION_NOTE,
  Listing.JSON_PROPERTY_COMMISSION_PAYER,
  Listing.JSON_PROPERTY_COMMISSION_PERCENT,
  Listing.JSON_PROPERTY_CURRENCY,
  Listing.JSON_PROPERTY_DEPOSIT,
  Listing.JSON_PROPERTY_HEATING_COSTS,
  Listing.JSON_PROPERTY_PRICE,
  Listing.JSON_PROPERTY_PRICE_ON_REQUEST,
  Listing.JSON_PROPERTY_PRICE_PER_SQM,
  Listing.JSON_PROPERTY_PRICE_PERIOD,
  Listing.JSON_PROPERTY_PUBLISHED_AT,
  Listing.JSON_PROPERTY_SERVICE_CHARGES,
  Listing.JSON_PROPERTY_STATUS,
  Listing.JSON_PROPERTY_TOTAL_RENT,
  Listing.JSON_PROPERTY_TRANSACTION_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Listing {
  public static final String JSON_PROPERTY_AVAILABLE_FROM = "available_from";
  @javax.annotation.Nullable
  private OffsetDateTime availableFrom;

  public static final String JSON_PROPERTY_COMMISSION_AMOUNT = "commission_amount";
  @javax.annotation.Nullable
  private BigDecimal commissionAmount;

  public static final String JSON_PROPERTY_COMMISSION_NOTE = "commission_note";
  @javax.annotation.Nullable
  private String commissionNote;

  public static final String JSON_PROPERTY_COMMISSION_PAYER = "commission_payer";
  @javax.annotation.Nullable
  private String commissionPayer;

  public static final String JSON_PROPERTY_COMMISSION_PERCENT = "commission_percent";
  @javax.annotation.Nullable
  private BigDecimal commissionPercent;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_DEPOSIT = "deposit";
  @javax.annotation.Nullable
  private BigDecimal deposit;

  public static final String JSON_PROPERTY_HEATING_COSTS = "heating_costs";
  @javax.annotation.Nullable
  private BigDecimal heatingCosts;

  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_PRICE_ON_REQUEST = "price_on_request";
  @javax.annotation.Nullable
  private Boolean priceOnRequest;

  public static final String JSON_PROPERTY_PRICE_PER_SQM = "price_per_sqm";
  @javax.annotation.Nullable
  private BigDecimal pricePerSqm;

  public static final String JSON_PROPERTY_PRICE_PERIOD = "price_period";
  @javax.annotation.Nullable
  private String pricePeriod;

  public static final String JSON_PROPERTY_PUBLISHED_AT = "published_at";
  @javax.annotation.Nullable
  private OffsetDateTime publishedAt;

  public static final String JSON_PROPERTY_SERVICE_CHARGES = "service_charges";
  @javax.annotation.Nullable
  private BigDecimal serviceCharges;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private String status;

  public static final String JSON_PROPERTY_TOTAL_RENT = "total_rent";
  @javax.annotation.Nullable
  private BigDecimal totalRent;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transaction_type";
  @javax.annotation.Nonnull
  private String transactionType;

  public Listing() { 
  }

  public Listing availableFrom(@javax.annotation.Nullable OffsetDateTime availableFrom) {
    this.availableFrom = availableFrom;
    return this;
  }

  /**
   * Get availableFrom
   * @return availableFrom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getAvailableFrom() {
    return availableFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableFrom(@javax.annotation.Nullable OffsetDateTime availableFrom) {
    this.availableFrom = availableFrom;
  }


  public Listing commissionAmount(@javax.annotation.Nullable BigDecimal commissionAmount) {
    this.commissionAmount = commissionAmount;
    return this;
  }

  /**
   * Get commissionAmount
   * @return commissionAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMISSION_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getCommissionAmount() {
    return commissionAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMISSION_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissionAmount(@javax.annotation.Nullable BigDecimal commissionAmount) {
    this.commissionAmount = commissionAmount;
  }


  public Listing commissionNote(@javax.annotation.Nullable String commissionNote) {
    this.commissionNote = commissionNote;
    return this;
  }

  /**
   * Get commissionNote
   * @return commissionNote
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMISSION_NOTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCommissionNote() {
    return commissionNote;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMISSION_NOTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissionNote(@javax.annotation.Nullable String commissionNote) {
    this.commissionNote = commissionNote;
  }


  public Listing commissionPayer(@javax.annotation.Nullable String commissionPayer) {
    this.commissionPayer = commissionPayer;
    return this;
  }

  /**
   * Get commissionPayer
   * @return commissionPayer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMISSION_PAYER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCommissionPayer() {
    return commissionPayer;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMISSION_PAYER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissionPayer(@javax.annotation.Nullable String commissionPayer) {
    this.commissionPayer = commissionPayer;
  }


  public Listing commissionPercent(@javax.annotation.Nullable BigDecimal commissionPercent) {
    this.commissionPercent = commissionPercent;
    return this;
  }

  /**
   * Get commissionPercent
   * @return commissionPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMISSION_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getCommissionPercent() {
    return commissionPercent;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMISSION_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissionPercent(@javax.annotation.Nullable BigDecimal commissionPercent) {
    this.commissionPercent = commissionPercent;
  }


  public Listing currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public Listing deposit(@javax.annotation.Nullable BigDecimal deposit) {
    this.deposit = deposit;
    return this;
  }

  /**
   * Get deposit
   * @return deposit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPOSIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getDeposit() {
    return deposit;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPOSIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeposit(@javax.annotation.Nullable BigDecimal deposit) {
    this.deposit = deposit;
  }


  public Listing heatingCosts(@javax.annotation.Nullable BigDecimal heatingCosts) {
    this.heatingCosts = heatingCosts;
    return this;
  }

  /**
   * Get heatingCosts
   * @return heatingCosts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEATING_COSTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getHeatingCosts() {
    return heatingCosts;
  }


  @JsonProperty(value = JSON_PROPERTY_HEATING_COSTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeatingCosts(@javax.annotation.Nullable BigDecimal heatingCosts) {
    this.heatingCosts = heatingCosts;
  }


  public Listing price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public Listing priceOnRequest(@javax.annotation.Nullable Boolean priceOnRequest) {
    this.priceOnRequest = priceOnRequest;
    return this;
  }

  /**
   * Get priceOnRequest
   * @return priceOnRequest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_ON_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPriceOnRequest() {
    return priceOnRequest;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_ON_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceOnRequest(@javax.annotation.Nullable Boolean priceOnRequest) {
    this.priceOnRequest = priceOnRequest;
  }


  public Listing pricePerSqm(@javax.annotation.Nullable BigDecimal pricePerSqm) {
    this.pricePerSqm = pricePerSqm;
    return this;
  }

  /**
   * Get pricePerSqm
   * @return pricePerSqm
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_PER_SQM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPricePerSqm() {
    return pricePerSqm;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_PER_SQM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricePerSqm(@javax.annotation.Nullable BigDecimal pricePerSqm) {
    this.pricePerSqm = pricePerSqm;
  }


  public Listing pricePeriod(@javax.annotation.Nullable String pricePeriod) {
    this.pricePeriod = pricePeriod;
    return this;
  }

  /**
   * Get pricePeriod
   * @return pricePeriod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE_PERIOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPricePeriod() {
    return pricePeriod;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE_PERIOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricePeriod(@javax.annotation.Nullable String pricePeriod) {
    this.pricePeriod = pricePeriod;
  }


  public Listing publishedAt(@javax.annotation.Nullable OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
    return this;
  }

  /**
   * Get publishedAt
   * @return publishedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PUBLISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getPublishedAt() {
    return publishedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishedAt(@javax.annotation.Nullable OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
  }


  public Listing serviceCharges(@javax.annotation.Nullable BigDecimal serviceCharges) {
    this.serviceCharges = serviceCharges;
    return this;
  }

  /**
   * Get serviceCharges
   * @return serviceCharges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getServiceCharges() {
    return serviceCharges;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_CHARGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceCharges(@javax.annotation.Nullable BigDecimal serviceCharges) {
    this.serviceCharges = serviceCharges;
  }


  public Listing status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public Listing totalRent(@javax.annotation.Nullable BigDecimal totalRent) {
    this.totalRent = totalRent;
    return this;
  }

  /**
   * Get totalRent
   * @return totalRent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_RENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTotalRent() {
    return totalRent;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_RENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRent(@javax.annotation.Nullable BigDecimal totalRent) {
    this.totalRent = totalRent;
  }


  public Listing transactionType(@javax.annotation.Nonnull String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Get transactionType
   * @return transactionType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionType(@javax.annotation.Nonnull String transactionType) {
    this.transactionType = transactionType;
  }


  /**
   * Return true if this Listing object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Listing listing = (Listing) o;
    return Objects.equals(this.availableFrom, listing.availableFrom) &&
        Objects.equals(this.commissionAmount, listing.commissionAmount) &&
        Objects.equals(this.commissionNote, listing.commissionNote) &&
        Objects.equals(this.commissionPayer, listing.commissionPayer) &&
        Objects.equals(this.commissionPercent, listing.commissionPercent) &&
        Objects.equals(this.currency, listing.currency) &&
        Objects.equals(this.deposit, listing.deposit) &&
        Objects.equals(this.heatingCosts, listing.heatingCosts) &&
        Objects.equals(this.price, listing.price) &&
        Objects.equals(this.priceOnRequest, listing.priceOnRequest) &&
        Objects.equals(this.pricePerSqm, listing.pricePerSqm) &&
        Objects.equals(this.pricePeriod, listing.pricePeriod) &&
        Objects.equals(this.publishedAt, listing.publishedAt) &&
        Objects.equals(this.serviceCharges, listing.serviceCharges) &&
        Objects.equals(this.status, listing.status) &&
        Objects.equals(this.totalRent, listing.totalRent) &&
        Objects.equals(this.transactionType, listing.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableFrom, commissionAmount, commissionNote, commissionPayer, commissionPercent, currency, deposit, heatingCosts, price, priceOnRequest, pricePerSqm, pricePeriod, publishedAt, serviceCharges, status, totalRent, transactionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Listing {\n");
    sb.append("    availableFrom: ").append(toIndentedString(availableFrom)).append("\n");
    sb.append("    commissionAmount: ").append(toIndentedString(commissionAmount)).append("\n");
    sb.append("    commissionNote: ").append(toIndentedString(commissionNote)).append("\n");
    sb.append("    commissionPayer: ").append(toIndentedString(commissionPayer)).append("\n");
    sb.append("    commissionPercent: ").append(toIndentedString(commissionPercent)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    deposit: ").append(toIndentedString(deposit)).append("\n");
    sb.append("    heatingCosts: ").append(toIndentedString(heatingCosts)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceOnRequest: ").append(toIndentedString(priceOnRequest)).append("\n");
    sb.append("    pricePerSqm: ").append(toIndentedString(pricePerSqm)).append("\n");
    sb.append("    pricePeriod: ").append(toIndentedString(pricePeriod)).append("\n");
    sb.append("    publishedAt: ").append(toIndentedString(publishedAt)).append("\n");
    sb.append("    serviceCharges: ").append(toIndentedString(serviceCharges)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalRent: ").append(toIndentedString(totalRent)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `available_from` to the URL query string
    if (getAvailableFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%savailable_from%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAvailableFrom()))));
    }

    // add `commission_amount` to the URL query string
    if (getCommissionAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommission_amount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommissionAmount()))));
    }

    // add `commission_note` to the URL query string
    if (getCommissionNote() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommission_note%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommissionNote()))));
    }

    // add `commission_payer` to the URL query string
    if (getCommissionPayer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommission_payer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommissionPayer()))));
    }

    // add `commission_percent` to the URL query string
    if (getCommissionPercent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommission_percent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommissionPercent()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `deposit` to the URL query string
    if (getDeposit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeposit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeposit()))));
    }

    // add `heating_costs` to the URL query string
    if (getHeatingCosts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sheating_costs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeatingCosts()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `price_on_request` to the URL query string
    if (getPriceOnRequest() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice_on_request%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPriceOnRequest()))));
    }

    // add `price_per_sqm` to the URL query string
    if (getPricePerSqm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice_per_sqm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPricePerSqm()))));
    }

    // add `price_period` to the URL query string
    if (getPricePeriod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice_period%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPricePeriod()))));
    }

    // add `published_at` to the URL query string
    if (getPublishedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spublished_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPublishedAt()))));
    }

    // add `service_charges` to the URL query string
    if (getServiceCharges() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sservice_charges%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceCharges()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `total_rent` to the URL query string
    if (getTotalRent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal_rent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalRent()))));
    }

    // add `transaction_type` to the URL query string
    if (getTransactionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransaction_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionType()))));
    }

    return joiner.toString();
  }
}

