/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skautik.sdk.model.Bounds;
import com.skautik.sdk.model.SearchFilters;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * SearchRequest
 */
@JsonPropertyOrder({
  SearchRequest.JSON_PROPERTY_BOUNDS,
  SearchRequest.JSON_PROPERTY_FILTERS,
  SearchRequest.JSON_PROPERTY_LIMIT,
  SearchRequest.JSON_PROPERTY_POLYGON,
  SearchRequest.JSON_PROPERTY_QUERY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SearchRequest {
  public static final String JSON_PROPERTY_BOUNDS = "bounds";
  @javax.annotation.Nullable
  private Bounds bounds;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @javax.annotation.Nonnull
  private SearchFilters filters;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_POLYGON = "polygon";
  @javax.annotation.Nonnull
  private List<List<BigDecimal>> polygon = new ArrayList<>();

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nonnull
  private String query;

  public SearchRequest() { 
  }

  public SearchRequest bounds(@javax.annotation.Nullable Bounds bounds) {
    this.bounds = bounds;
    return this;
  }

  /**
   * Get bounds
   * @return bounds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOUNDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Bounds getBounds() {
    return bounds;
  }


  @JsonProperty(value = JSON_PROPERTY_BOUNDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBounds(@javax.annotation.Nullable Bounds bounds) {
    this.bounds = bounds;
  }


  public SearchRequest filters(@javax.annotation.Nonnull SearchFilters filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Get filters
   * @return filters
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SearchFilters getFilters() {
    return filters;
  }


  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilters(@javax.annotation.Nonnull SearchFilters filters) {
    this.filters = filters;
  }


  public SearchRequest limit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@javax.annotation.Nonnull Integer limit) {
    this.limit = limit;
  }


  public SearchRequest polygon(@javax.annotation.Nonnull List<List<BigDecimal>> polygon) {
    this.polygon = polygon;
    return this;
  }

  public SearchRequest addPolygonItem(List<BigDecimal> polygonItem) {
    if (this.polygon == null) {
      this.polygon = new ArrayList<>();
    }
    this.polygon.add(polygonItem);
    return this;
  }

  /**
   * Get polygon
   * @return polygon
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POLYGON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<List<BigDecimal>> getPolygon() {
    return polygon;
  }


  @JsonProperty(value = JSON_PROPERTY_POLYGON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolygon(@javax.annotation.Nonnull List<List<BigDecimal>> polygon) {
    this.polygon = polygon;
  }


  public SearchRequest query(@javax.annotation.Nonnull String query) {
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuery(@javax.annotation.Nonnull String query) {
    this.query = query;
  }


  /**
   * Return true if this SearchRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequest searchRequest = (SearchRequest) o;
    return Objects.equals(this.bounds, searchRequest.bounds) &&
        Objects.equals(this.filters, searchRequest.filters) &&
        Objects.equals(this.limit, searchRequest.limit) &&
        Objects.equals(this.polygon, searchRequest.polygon) &&
        Objects.equals(this.query, searchRequest.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounds, filters, limit, polygon, query);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequest {\n");
    sb.append("    bounds: ").append(toIndentedString(bounds)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    polygon: ").append(toIndentedString(polygon)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `bounds` to the URL query string
    if (getBounds() != null) {
      joiner.add(getBounds().toUrlQueryString(prefix + "bounds" + suffix));
    }

    // add `filters` to the URL query string
    if (getFilters() != null) {
      joiner.add(getFilters().toUrlQueryString(prefix + "filters" + suffix));
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `polygon` to the URL query string
    if (getPolygon() != null) {
      for (int i = 0; i < getPolygon().size(); i++) {
        if (getPolygon().get(i) != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%spolygon%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getPolygon().get(i)))));
        }
      }
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    return joiner.toString();
  }
}

