/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * SeriesPoint
 */
@JsonPropertyOrder({
  SeriesPoint.JSON_PROPERTY_LISTING_COUNT,
  SeriesPoint.JSON_PROPERTY_MEDIAN_DAYS_LISTED,
  SeriesPoint.JSON_PROPERTY_MEDIAN_PRICE,
  SeriesPoint.JSON_PROPERTY_MEDIAN_PRICE_PER_AREA,
  SeriesPoint.JSON_PROPERTY_PERIOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SeriesPoint {
  public static final String JSON_PROPERTY_LISTING_COUNT = "listing_count";
  @javax.annotation.Nonnull
  private Integer listingCount;

  public static final String JSON_PROPERTY_MEDIAN_DAYS_LISTED = "median_days_listed";
  @javax.annotation.Nullable
  private Integer medianDaysListed;

  public static final String JSON_PROPERTY_MEDIAN_PRICE = "median_price";
  @javax.annotation.Nullable
  private BigDecimal medianPrice;

  public static final String JSON_PROPERTY_MEDIAN_PRICE_PER_AREA = "median_price_per_area";
  @javax.annotation.Nullable
  private BigDecimal medianPricePerArea;

  public static final String JSON_PROPERTY_PERIOD = "period";
  @javax.annotation.Nonnull
  private String period;

  public SeriesPoint() { 
  }

  public SeriesPoint listingCount(@javax.annotation.Nonnull Integer listingCount) {
    this.listingCount = listingCount;
    return this;
  }

  /**
   * Get listingCount
   * @return listingCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LISTING_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getListingCount() {
    return listingCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LISTING_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setListingCount(@javax.annotation.Nonnull Integer listingCount) {
    this.listingCount = listingCount;
  }


  public SeriesPoint medianDaysListed(@javax.annotation.Nullable Integer medianDaysListed) {
    this.medianDaysListed = medianDaysListed;
    return this;
  }

  /**
   * Get medianDaysListed
   * @return medianDaysListed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIAN_DAYS_LISTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMedianDaysListed() {
    return medianDaysListed;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDIAN_DAYS_LISTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedianDaysListed(@javax.annotation.Nullable Integer medianDaysListed) {
    this.medianDaysListed = medianDaysListed;
  }


  public SeriesPoint medianPrice(@javax.annotation.Nullable BigDecimal medianPrice) {
    this.medianPrice = medianPrice;
    return this;
  }

  /**
   * Get medianPrice
   * @return medianPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIAN_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getMedianPrice() {
    return medianPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDIAN_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedianPrice(@javax.annotation.Nullable BigDecimal medianPrice) {
    this.medianPrice = medianPrice;
  }


  public SeriesPoint medianPricePerArea(@javax.annotation.Nullable BigDecimal medianPricePerArea) {
    this.medianPricePerArea = medianPricePerArea;
    return this;
  }

  /**
   * Get medianPricePerArea
   * @return medianPricePerArea
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIAN_PRICE_PER_AREA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getMedianPricePerArea() {
    return medianPricePerArea;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDIAN_PRICE_PER_AREA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedianPricePerArea(@javax.annotation.Nullable BigDecimal medianPricePerArea) {
    this.medianPricePerArea = medianPricePerArea;
  }


  public SeriesPoint period(@javax.annotation.Nonnull String period) {
    this.period = period;
    return this;
  }

  /**
   * Get period
   * @return period
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPeriod() {
    return period;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriod(@javax.annotation.Nonnull String period) {
    this.period = period;
  }


  /**
   * Return true if this SeriesPoint object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeriesPoint seriesPoint = (SeriesPoint) o;
    return Objects.equals(this.listingCount, seriesPoint.listingCount) &&
        Objects.equals(this.medianDaysListed, seriesPoint.medianDaysListed) &&
        Objects.equals(this.medianPrice, seriesPoint.medianPrice) &&
        Objects.equals(this.medianPricePerArea, seriesPoint.medianPricePerArea) &&
        Objects.equals(this.period, seriesPoint.period);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listingCount, medianDaysListed, medianPrice, medianPricePerArea, period);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeriesPoint {\n");
    sb.append("    listingCount: ").append(toIndentedString(listingCount)).append("\n");
    sb.append("    medianDaysListed: ").append(toIndentedString(medianDaysListed)).append("\n");
    sb.append("    medianPrice: ").append(toIndentedString(medianPrice)).append("\n");
    sb.append("    medianPricePerArea: ").append(toIndentedString(medianPricePerArea)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `listing_count` to the URL query string
    if (getListingCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slisting_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getListingCount()))));
    }

    // add `median_days_listed` to the URL query string
    if (getMedianDaysListed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smedian_days_listed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMedianDaysListed()))));
    }

    // add `median_price` to the URL query string
    if (getMedianPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smedian_price%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMedianPrice()))));
    }

    // add `median_price_per_area` to the URL query string
    if (getMedianPricePerArea() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smedian_price_per_area%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMedianPricePerArea()))));
    }

    // add `period` to the URL query string
    if (getPeriod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%speriod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPeriod()))));
    }

    return joiner.toString();
  }
}

