/*
 * Skautik Partner API
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.skautik.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.skautik.sdk.ApiClient;
/**
 * SourceUpdate
 */
@JsonPropertyOrder({
  SourceUpdate.JSON_PROPERTY_ACTIVE,
  SourceUpdate.JSON_PROPERTY_DELETION_POLICY,
  SourceUpdate.JSON_PROPERTY_FETCH_URL,
  SourceUpdate.JSON_PROPERTY_MAPPING,
  SourceUpdate.JSON_PROPERTY_NAME,
  SourceUpdate.JSON_PROPERTY_SCHEDULE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SourceUpdate {
  public static final String JSON_PROPERTY_ACTIVE = "active";
  @javax.annotation.Nullable
  private Boolean active;

  public static final String JSON_PROPERTY_DELETION_POLICY = "deletion_policy";
  @javax.annotation.Nullable
  private String deletionPolicy;

  public static final String JSON_PROPERTY_FETCH_URL = "fetch_url";
  @javax.annotation.Nullable
  private String fetchUrl;

  public static final String JSON_PROPERTY_MAPPING = "mapping";
  @javax.annotation.Nullable
  private Map<String, String> mapping = new HashMap<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SCHEDULE = "schedule";
  @javax.annotation.Nullable
  private String schedule;

  public SourceUpdate() { 
  }

  public SourceUpdate active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getActive() {
    return active;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public SourceUpdate deletionPolicy(@javax.annotation.Nullable String deletionPolicy) {
    this.deletionPolicy = deletionPolicy;
    return this;
  }

  /**
   * Get deletionPolicy
   * @return deletionPolicy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETION_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeletionPolicy() {
    return deletionPolicy;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETION_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletionPolicy(@javax.annotation.Nullable String deletionPolicy) {
    this.deletionPolicy = deletionPolicy;
  }


  public SourceUpdate fetchUrl(@javax.annotation.Nullable String fetchUrl) {
    this.fetchUrl = fetchUrl;
    return this;
  }

  /**
   * Get fetchUrl
   * @return fetchUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FETCH_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFetchUrl() {
    return fetchUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_FETCH_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFetchUrl(@javax.annotation.Nullable String fetchUrl) {
    this.fetchUrl = fetchUrl;
  }


  public SourceUpdate mapping(@javax.annotation.Nullable Map<String, String> mapping) {
    this.mapping = mapping;
    return this;
  }

  public SourceUpdate putMappingItem(String key, String mappingItem) {
    if (this.mapping == null) {
      this.mapping = new HashMap<>();
    }
    this.mapping.put(key, mappingItem);
    return this;
  }

  /**
   * Get mapping
   * @return mapping
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getMapping() {
    return mapping;
  }


  @JsonProperty(value = JSON_PROPERTY_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapping(@javax.annotation.Nullable Map<String, String> mapping) {
    this.mapping = mapping;
  }


  public SourceUpdate name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public SourceUpdate schedule(@javax.annotation.Nullable String schedule) {
    this.schedule = schedule;
    return this;
  }

  /**
   * Get schedule
   * @return schedule
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSchedule() {
    return schedule;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedule(@javax.annotation.Nullable String schedule) {
    this.schedule = schedule;
  }


  /**
   * Return true if this SourceUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceUpdate sourceUpdate = (SourceUpdate) o;
    return Objects.equals(this.active, sourceUpdate.active) &&
        Objects.equals(this.deletionPolicy, sourceUpdate.deletionPolicy) &&
        Objects.equals(this.fetchUrl, sourceUpdate.fetchUrl) &&
        Objects.equals(this.mapping, sourceUpdate.mapping) &&
        Objects.equals(this.name, sourceUpdate.name) &&
        Objects.equals(this.schedule, sourceUpdate.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, deletionPolicy, fetchUrl, mapping, name, schedule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceUpdate {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    deletionPolicy: ").append(toIndentedString(deletionPolicy)).append("\n");
    sb.append("    fetchUrl: ").append(toIndentedString(fetchUrl)).append("\n");
    sb.append("    mapping: ").append(toIndentedString(mapping)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `active` to the URL query string
    if (getActive() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactive%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActive()))));
    }

    // add `deletion_policy` to the URL query string
    if (getDeletionPolicy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeletion_policy%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeletionPolicy()))));
    }

    // add `fetch_url` to the URL query string
    if (getFetchUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfetch_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFetchUrl()))));
    }

    // add `mapping` to the URL query string
    if (getMapping() != null) {
      for (String _key : getMapping().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smapping%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getMapping().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getMapping().get(_key)))));
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `schedule` to the URL query string
    if (getSchedule() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sschedule%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSchedule()))));
    }

    return joiner.toString();
  }
}

